---
title: "sf11_v2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r}
#Load in libraries 
library(tidyverse)
library(rio)
library(plyr)
library(dplyr)
library(fs)
library(lme4)
library(lmerTest)
library(psych)
options(scipen=999)
library(ggplot2)
library(sjPlot)
```



```{r}
#loading in data 

switch11_v2 <- import("switchfreq_11_main_v2_2_raw_21_04_13.csv")

#remove subjects that need to be excluded 
exclude_subjects <- c('3877', '3897', '3900', '3917', '3934', '3952', '3956', 
                      '3966', '3968', '3974', '3982', '4016', '4037', '4087', 
                      '4095', '4118', '4121', '4123', '4133', '4134', '4139', 
                      '4161', '4172', '4210', '4214', '4227', '4243')

switch11_v2_use <- switch11_v2 %>%
  filter(!subject %in% exclude_subjects)
  


sf11_v2_total_encodingonly <-  switch11_v2_use %>% 
  filter(str_detect(trialcode, "image"))
```


```{r}
#add columns to dataset 

sf11_v2_total_encodingonly_new <- sf11_v2_total_encodingonly %>% 
  separate(blockcode, c("condition", "between_condition"), remove = FALSE) %>% 
    mutate(between_condition = case_when(between_condition == "same" ~ "same",
                                         between_condition == "same2" ~"same",
                                         between_condition == "novel" ~"novel",
                                         between_condition == "novel2" ~"novel")) %>% 
  mutate(blocknum_contin = case_when(blocknum == "13" ~ "1",
                                         blocknum == "17" ~"2",
                                         blocknum == "21" ~"3",
                                         blocknum == "25" ~"4",
                                      blocknum == "29" ~ "5",
                                         blocknum == "33" ~"6")) %>% 
   mutate(list_half = case_when(trialnum == "1" ~ "first_half",
                                         trialnum == "2" ~"first_half",
                                         trialnum == "3" ~"first_half",
                                         trialnum == "4" ~"first_half",
                                         trialnum == "5" ~ "first_half",
                                         trialnum == "6" ~"first_half",
                                         trialnum == "7" ~"first_half",
                                         trialnum == "8" ~"second_half",
                                         trialnum == "9" ~"second_half",
                                         trialnum == "10" ~"second_half",
                                         trialnum == "11" ~"second_half",
                                         trialnum == "12" ~ "second_half",
                                         trialnum == "13" ~"second_half",
                                         trialnum == "14" ~"second_half",
                                         trialnum == "15" ~"second_half",
                                          trialnum == "16" ~"second_half")) %>% 
   mutate(pool_number = case_when(word_enc == "ACORN"~ 1, 
word_enc == "ANCHOR"~	2,
word_enc =="APPLE"	~3,
word_enc =="APRON"	~4, 
word_enc =="ARROW"~	5,
word_enc =="ATLAS"~	6,
word_enc =="BACON"~	7,
word_enc =="BAKER"~	8,
word_enc =="BANDAGE"~ 9,
word_enc =="BANJO"~	10,
word_enc =="BANKER"~	11,
word_enc =="BARLEY"~	12,
word_enc =="BARREL"~	13,
word_enc =="BASEBALL"~	14,
word_enc =="BEAKER"~	15,
word_enc =="BEAVER"~	16,
word_enc =="BEETLE"~	17,
word_enc =="BERRY"~	18,
word_enc =="BINDER"~	19,
word_enc =="BISCUIT"~	20,
word_enc =="BISON"~	21,
word_enc =="BLACKBOARD"~	22,
word_enc =="BLENDER"~	23,
word_enc =="BOTTLE"~	24,
word_enc =="BRACELET"~	25,
word_enc =="BRIEFCASE"~	26,
word_enc =="BUILDING"~	27,
word_enc =="BUTLER"~	28,
word_enc =="BUTTER"~	29,
word_enc =="BUTTON"~	30,
word_enc =="CABBAGE"~	31,
word_enc =="CACTUS"~	32,
word_enc =="CAMEL"~	33,
word_enc =="CANDY"~	34,
word_enc =="CANOE"~	35,
word_enc =="CANVAS"~	36,
word_enc =="CARPET"~	37,
word_enc =="CARROT"~	38,
word_enc =="CARTON"~	39,
word_enc =="CASTLE"~	40,
word_enc =="CATTLE"~	41,
word_enc =="CELLO"~	42,
word_enc =="CHECKERS"~	43,
word_enc =="CHEDDAR"~	44,
word_enc =="CHERRY"~	45,
word_enc =="CHICKEN"~	46,
word_enc =="CHIPMUNK"~	47,
word_enc =="CLOSET"~	48,
word_enc =="COFFEE"~	49,
word_enc =="COMPASS"~	50,
word_enc =="COOKBOOK"~	51,
word_enc =='COOKIE'~	52,
word_enc =="COOLER"~	53,
word_enc =="CORAL"~	54,
word_enc =="COTTAGE"~	55,
word_enc =="COTTON"~	56,
word_enc =="CRACKER"~	57,
word_enc =="CRAYON"~	58,
word_enc =="CRICKET"~	59,
word_enc =="CRYSTAL"~	60,
word_enc =="CURTAIN"~	61,
word_enc =="CUSHION"~	62,
word_enc =="DAISY"~	63,
word_enc =="DENIM"~	64,
word_enc =="DENTIST"~	65,
word_enc =="DESSERT"~	66,
word_enc =="DIAPER"~	67,
word_enc =="DINNER"~	68,
word_enc =="DOLLAR"~	69,
word_enc =="DOLPHIN"~	70,
word_enc =="DONKEY"~	71,
word_enc =="DOORBELL"~	72,
word_enc =="DOUGHNUT"~	73,
word_enc =="DRAWING"~	74,
word_enc =="DRESSER"~	75,
word_enc =="DRIVEWAY"~	76,
word_enc =="DUSTPAN"~	77,
word_enc =="EAGLE"~	78,
word_enc =="EARRING"~	79,
word_enc =="ENGINE"~	80,
word_enc =="ESSAY"~	81,
word_enc =="FAUCET"~	82,
word_enc =="FEATHER"~	83,
word_enc =="FLANNEL"~	84,
word_enc =="FLASHLIGHT"~	85,
word_enc =="FOLDER"~	86,
word_enc =="FOOTBALL"~	87,
word_enc =="FOREST"~	88,
word_enc =="FOSSIL"~	89,
word_enc =="FOUNTAIN"~	90,
word_enc =="FREEZER"~	91,
word_enc =="GARBAGE"~	92,
word_enc =="GARDEN"~	93,
word_enc =="GARLIC"~	94,
word_enc =="GIRAFFE"~	95,
word_enc =="GUITAR"~	96,
word_enc =="GYMNAST"~	97,
word_enc =="HAMMER"~	98,
word_enc =="HAMMOCK"~	99,
word_enc =="HAMPER"~	100,
word_enc =="HANDBAG"~	101,
word_enc =="HANGER"~	102,
word_enc =="HEADBAND"~	103,
word_enc =="HELMET"~	104,
word_enc =="HIGHWAY"~	105,
word_enc =="HIKER"~	106,
word_enc =="HONEY"~	107,
word_enc =="IRON"~	108,
word_enc =="JACKET"~	109,
word_enc =="JELLY"~	110,
word_enc =="JEWEL"~	111,
word_enc =="KETCHUP"~	112,
word_enc =="KETTLE"~	113,
word_enc =="KEYBOARD"~	114,
word_enc =="KITCHEN"~	115,
word_enc =="LADDER"~	116,
word_enc =="LAUNDRY"~	117,
word_enc =="LAVA"~	118,
word_enc =="LAWYER"~	119,
word_enc =="LEMON"~	120,
word_enc =="LEOPARD"~	121,
word_enc =="LETTER"~	122,
word_enc =="LETTUCE"~	123,
word_enc =="LINEN"~	124,
word_enc =="LION"~	125,
word_enc =="LIPSTICK"~	126,
word_enc =="LITTER"~	127,
word_enc =="LIZARD"~	128,
word_enc =="LUGGAGE"~	129,
word_enc =="LUMBER"~	130,
word_enc =="MACHINE"~	131,
word_enc =="MAILBOX"~	132,
word_enc =="MARBLE"~	133,
word_enc =="MATTRESS"~	134,
word_enc =="MIRROR"~	135,
word_enc =="MITTEN"~	136,
word_enc =="MONKEY"~	137,
word_enc =="MOUNTAIN"~	138,
word_enc =="MUFFIN"~	139,
word_enc =="MUSHROOM"~	140,
word_enc =="NAPKIN"~	141,
word_enc =="NECKLACE"~	142,
word_enc =="NEEDLE"~	143,
word_enc =="NICKEL"~	144,
word_enc =="NOVEL"~	145,
word_enc =="OATMEAL"~	146,
word_enc =="OLIVE"~	147,
word_enc =="OMELET"~	148,
word_enc =="ONION"~	149,
word_enc =="ORANGE"~	150,
word_enc =="ORCHID"~	151,
word_enc =="OTTER"~	152,
word_enc =="OUTFIT"~	153,
word_enc =="OVEN"~	154,
word_enc =="OWL"~	155,
word_enc =="OYSTER"~	156,
word_enc =="PACKAGE"~	157,
word_enc =="PADDLE"~	158,
word_enc =="PAINTING"~	159,
word_enc =="PANTHER"~	160,
word_enc =="PARSLEY"~	161,
word_enc =="PASTA"~	162,
word_enc =="PASTRY"~	163,
word_enc =="PEANUT"~	164,
word_enc =="PEBBLE"~	165,
word_enc =="PENCIL"~	166,
word_enc =="PENGUIN"~	167,
word_enc =="PENNY"~	168,
word_enc =="PEPPER"~	169,
word_enc =="PICKLE"~	170,
word_enc =="PICNIC"~	171,
word_enc =="PIGEON"~	172,
word_enc =="PILLOW"~	173,
word_enc =="PILOT"~	174,
word_enc =="PIZZA"~	175,
word_enc =="PLANET"~	176,
word_enc =="PLAYGROUND"~	177,
word_enc =="POPCORN"~	178,
word_enc =="POSSUM"~	179,
word_enc =="PRINTER"~	180,
word_enc =="PUDDING"~	181,
word_enc =="PUDDLE"~	182,
word_enc =="PUMPKIN"~	183,
word_enc =='PUZZLE'~	184,
word_enc =="RABBIT"~	185,
word_enc =="RACCOON"~	186,
word_enc =="RACKET"~	187,
word_enc =="RADISH"~	188,
word_enc =="RAILROAD"~	189,
word_enc =="RAISIN"~	190,
word_enc =="RATTLE"~	191,
word_enc =="RECEIPT"~	192,
word_enc =="RECORD"~	193,
word_enc =="REPORT"~	194,
word_enc =="RIBBON"~	195,
word_enc =="RIVER"~	196,
word_enc =="ROBOT"~	197,
word_enc =="RUNNER"~	198,
word_enc =="SADDLE"~	199,
word_enc =="SAILOR"~	200,
word_enc =="SALAD"~	201,
word_enc =="SALMON"~	202,
word_enc =="SANDWICH"~	203,
word_enc =="SEAFOOD"~	204,
word_enc =="SEASHORE"~	205,
word_enc =="SHAMPOO"~	206,
word_enc =="SHOELACE"~	207,
word_enc =="SHOVEL"~	208,
word_enc =="SHOWER"~	209,
word_enc =="SIDEWALK"~	210,
word_enc =="SNORKEL"~	211,
word_enc =="SODA"~	212,
word_enc =="SOFA"~	213,
word_enc =="SQUIRREL"~	214,
word_enc =="STATUE"~	215,
word_enc =="STICKER"~	216,
word_enc =="STOCKING"~	217,
word_enc =="SUGAR"~	218,
word_enc =="SUITCASE"~	219,
word_enc =="SUNRISE"~	220,
word_enc =="SWEATER"~	221,
word_enc =="TABLE"~	222,
word_enc =="TEACHER"~	223,
word_enc =="TOASTER"~	224,
word_enc =="TOOTHBRUSH"~	225,
word_enc =="TOURIST"~	226,
word_enc =="TOWEL"~	227,
word_enc =="TOWER"~	228,
word_enc =="TUBA"~	229,
word_enc =="TULIP"~	230,
word_enc =="TURNIP"~	231,
word_enc =="TURTLE"~	232,
word_enc =="VACUUM"~	233,
word_enc =="VALLEY"~	234,
word_enc =="VELVET"~	235,
word_enc =="WAGON"~	236,
word_enc =="WALNUT"~	237,
word_enc =="WALRUS"~	238,
word_enc =="WASHCLOTH"~	239,
word_enc =="ZIPPER"~	240))

sf11_v2_total_encodingonly_new$blocknum_contin <- as.integer(sf11_v2_total_encodingonly_new$blocknum_contin )

  
  
```




```{r}
#encoding task 

detach(package:Rmisc)
detach(package:plyr)


Mode <- function(x) {
  ux <- unique(x)
  ux[which.max(tabulate(match(x, ux)))]
}


encoding_sf11_v2_avg <- sf11_v2_total_encodingonly_new %>% 
  group_by(image, word_enc) %>% 
  mutate(resp_mode = Mode(response)) %>%  #takes the mode of responses based on word and trial 
  mutate(similar_to_avg = case_when(response == resp_mode ~ 1, #when the response is the mode - 1
                               response != resp_mode ~ 0)) %>% #when response is not the mode - 0
  arrange(subject, blocknum) %>% #arranges it back by subject 
  group_by(subject, blocknum) %>% 
  mutate(sum_encoding_sim = sum(similar_to_avg)) #creates a sum by block 
encoding_sf11_v2_avg

encoding_sf11_v2_avg %>% 
  group_by(subject, blocknum) %>% 
  summarise(mean_enc_num = mean(sum_encoding_sim))


encoding_sf11_v2_avg_image <- encoding_sf11_v2_avg %>% 
  group_by(image) %>% 
  summarise(mean_enc_code = mean(sum_encoding_sim))



encoding_sf11_v2_avg_2 <- encoding_sf11_v2_avg %>% 
  group_by(subject) %>% 
  mutate(similar_to_avg_percent = sum(similar_to_avg)/96*100) %>% 
  summarise(mean_enc = mean(similar_to_avg_percent, na.rm = TRUE))

#Calculate average encoding not based on trialcode, but based on actual stimuli on the screen (in column "image"). This is because of the way I coded it, the item in trialcode maps to multiple images. Therefore, Image is the column needed to determine which "task" the participants are performing on that trial 

#sig above is chance is 58.3% for 96 trials 
#chance is 68.8% for 16 trials 


mean_encoding_11_v2 <- mean(encoding_sf11_v2_avg_2$mean_enc, na.rm = TRUE)
mean_encoding_11_v2

```



```{r}

#compare means between same and novel 
encoding_sf11_v2_avg_3 <- encoding_sf11_v2_avg %>% 
  group_by(subject, between_condition) %>% 
  mutate(similar_to_avg_percent = sum(similar_to_avg)/96*100) %>% 
  summarise(mean_enc = mean(similar_to_avg_percent, na.rm = TRUE))

mean_encoding_11_v2_2 <- mean(encoding_sf11_v2_avg_3$mean_enc, na.rm = TRUE)
mean_encoding_11_v2_2


encoding_sf11_v2_avg_3_same <- encoding_sf11_v2_avg_3 %>% 
  filter(between_condition == "same")

mean_encoding_11_same_v2 <- mean(encoding_sf11_v2_avg_3_same$mean_enc, na.rm = TRUE)
mean_encoding_11_same_v2


sd_same2 <-sd(encoding_sf11_v2_avg_3_same$mean_enc, na.rm = TRUE)
sd_same2

se_same2 <- sd_same2 / sqrt(83)
se_same2

encoding_sf11_v2_avg_3_novel <- encoding_sf11_v2_avg_3 %>% 
  filter(between_condition == "novel")

mean_encoding_11_novel2 <- mean(encoding_sf11_v2_avg_3_novel$mean_enc, na.rm = TRUE)
mean_encoding_11_novel2


sd_novel2 <-sd(encoding_sf11_v2_avg_3_novel$mean_enc, na.rm = TRUE)
sd_novel2

se_novel2 <- sd_novel / sqrt(84)
se_novel2


t.test(encoding_sf11_v2_avg_3_same$mean_enc, encoding_sf11_v2_avg_3_novel$mean_enc)

cohensD(mean_enc~ between_condition, encoding_sf11_v2_avg_3)
```



```{r}
#adding in task_switch column 

sf11_v2_total_encodingonly_new2 <- encoding_sf11_v2_avg %>% 
  mutate(task_switch = case_when(condition == "control" & trialnum == "1" ~ "start",
                                         condition == "control"& trialnum == "2" ~"repeat",
                                 condition == "control"& trialnum == "3" ~"repeat",
                                 condition == "control"& trialnum == "4" ~"repeat",
                                 condition == "control"& trialnum == "5" ~"repeat",
                                 condition == "control"& trialnum == "6" ~"repeat",
                                 condition == "control"& trialnum == "7" ~"repeat",
                                 condition == "control"& trialnum == "8" ~"repeat",
                                 condition == "control"& trialnum == "9" ~"repeat",
                                 condition == "control"& trialnum == "10" ~"repeat",
                                 condition == "control"& trialnum == "11" ~"repeat",
                                 condition == "control"& trialnum == "12" ~"repeat",
                                 condition == "control"& trialnum == "13" ~"repeat",
                                 condition == "control"& trialnum == "14" ~"repeat",
                                 condition == "control"& trialnum == "15" ~"repeat",
                                 condition == "control"& trialnum == "16" ~"repeat",
                                 condition == "high" & trialnum == "1" ~ "start",
                                condition == "high"& trialnum == "2" ~"repeat",
                                 condition == "high"& trialnum == "3" ~"switch",
                                 condition == "high"& trialnum == "4" ~"repeat",
                                 condition == "high"& trialnum == "5" ~"switch",
                                 condition == "high"& trialnum == "6" ~"repeat",
                                 condition == "high"& trialnum == "7" ~"switch",
                                 condition == "high"& trialnum == "8" ~"repeat",
                                 condition == "high"& trialnum == "9" ~"switch",
                                 condition == "high"& trialnum == "10" ~"repeat",
                                 condition == "high"& trialnum == "11" ~"switch",
                                 condition == "high"& trialnum == "12" ~"repeat",
                                 condition == "high"& trialnum == "13" ~"switch",
                                 condition == "high"& trialnum == "14" ~"repeat",
                                 condition == "high"& trialnum == "15" ~"switch",
                                 condition == "high"& trialnum == "16" ~"repeat",
                                condition == "mid" & trialnum == "1" ~ "start",
                                 condition == "mid"& trialnum == "2" ~"repeat",
                                 condition == "mid"& trialnum == "3" ~"repeat",
                                 condition == "mid"& trialnum == "4" ~"repeat",
                                 condition == "mid"& trialnum == "5" ~"switch",
                                 condition == "mid"& trialnum == "6" ~"repeat",
                                 condition == "mid"& trialnum == "7" ~"repeat",
                                 condition == "mid"& trialnum == "8" ~"repeat",
                                 condition == "mid"& trialnum == "9" ~"switch",
                                 condition == "mid"& trialnum == "10" ~"repeat",
                                 condition == "mid"& trialnum == "11" ~"repeat",
                                 condition == "mid"& trialnum == "12" ~"repeat",
                                 condition == "mid"& trialnum == "13" ~"switch",
                                 condition == "mid"& trialnum == "14" ~"repeat",
                                 condition == "mid"& trialnum == "15" ~"repeat",
                                 condition == "mid"& trialnum == "16" ~"repeat"))
```







```{r}
#create separate dataframes for between subjects manipulations
#between subjects manipulation here is same vs novel NOT high vs mid 

sf11_v2_total_encodingonly_same <-sf11_v2_total_encodingonly_new2 %>% 
  filter(between_condition == "same")


sf11_v2_total_encodingonly_novel <-sf11_v2_total_encodingonly_new2 %>% 
  filter(between_condition == "novel")
```




```{r}
#sets path to data
#changes ann files to txt files 
path_to_data <- "~/Documents/DuBrow_lab/Projects/Multitasking/switchfreq_11/V2/Raw_Data"
setwd(path_to_data)
ann_files <- list.files(path_to_data, recursive = TRUE, pattern = "*.ann", full.names = TRUE)
text_files <- gsub(".ann", ".txt", ann_files)
text_files
file.rename(from= ann_files, to = text_files)
```



```{r}
library(plyr)

# Define the list of subject IDs explicitly
subjects <- c("3878", "3879", "3880", "3882", "3885", "3886", "3893", "3895", "3896", 
  "3902", "3905", "3907", "3908", "3913", "3916", "3918", "3919", "3927", 
  "3928", "3929", "3935", "3938", "3939", "3940", "3943", "3944", "3945", 
  "3946", "3948", "3949", "3953", "3954", "3955", "3957", "3958", "3959", 
  "3960", "3964", "3967", "3969", "3971", "3973", "3976", "3977", "3980", 
  "3981", "3983", "3984", "3989", "3990", "3991", "3992", "3993", "4002", 
  "4006", "4007", "4008", "4010", "4011", "4012", "4013", "4014", "4017", 
  "4019", "4021", "4024", "4025", "4026", "4027", "4028", "4030", "4034", 
  "4038", "4039", "4046", "4048", "4049", "4051", "4052", "4053", "4055", 
  "4056", "4057", "4059", "4063", "4068", "4071", "4074", "4076", "4078", 
  "4079", "4080", "4081", "4089", "4090", "4092", "4093", "4094", "4096", 
  "4097", "4098", "4101", "4102", "4103", "4104", "4106", "4108", "4109", 
  "4115", "4116", "4119", "4122", "4124", "4126", "4127", "4129", "4130", 
  "4132", "4135", "4137", "4138", "4140", "4141", "4147", "4148", "4149", 
  "4151", "4154", "4156", "4159", "4160", "4165", "4166", "4169", "4171", 
  "4173", "4175", "4176", "4177", "4179", "4180", "4182", "4183", "4185", 
  "4186", "4187", "4192", "4193", "4194", "4196", "4202", "4206", "4211", 
  "4213", "4216", "4217", "4219", "4220", "4222", "4224", "4225", "4229", 
  "4230", "4238", "4239", "4242", "4153")

process_subject_data <- function(subject_id) {
  # Define the path to the subject's recall files
  recall_files <- dir_ls(paste0("~/Documents/DuBrow_lab/Projects/Multitasking/switchfreq_11/V2/Raw_Data/", subject_id), glob = "*.txt")
  
  # Load the recall data
  recall_data <- ldply(recall_files, import)
  
  # Clean the .id column
  recall_data <- recall_data %>% 
    mutate(.id = str_replace_all(.id, "/Users/lrait/Documents/DuBrow_lab/Projects/Multitasking/switchfreq_11/V2/Raw_Data/", ""))
  
  # Separate final recall data and other recall data
  final_recall <- recall_data %>% 
    filter(.id == paste0(subject_id, "/", "finalrecall.txt"))
  
  recall <- recall_data %>% 
    filter(!grepl(paste0(subject_id, "/",  "finalrecall.txt"), .id))
  
  list(final_recall = final_recall, recall = recall)
}

# Process data for each subject and assign to individual variables
for (subject_id in subjects) {
  data <- process_subject_data(subject_id)
  
  assign(paste0("final_recall_", subject_id), data$final_recall)
  assign(paste0("recall_", subject_id), data$recall)
}
```



```{r}
#most important code chunk.- immediate recall 
library(stringr)
detach(package:Rmisc) 
detach(package:plyr) #MUST RUN THIS

split_enc_11_v2 <- split(sf11_v2_total_encodingonly_new2,sf11_v2_total_encodingonly_new2$subject)

#list of all subjects individual recall data
recall11_df_immed_2 = list(recall_3878, recall_3879, recall_3880, recall_3882, recall_3885, recall_3886, recall_3893, recall_3895, recall_3896, recall_3902, recall_3905, recall_3907, recall_3908, recall_3913, recall_3916, recall_3918, recall_3919, recall_3927, recall_3928, recall_3929, recall_3935, recall_3938, recall_3939, recall_3940, recall_3943, recall_3944, recall_3945, recall_3946, recall_3948, recall_3949, recall_3953, recall_3954, recall_3955, recall_3957, recall_3958, recall_3959, recall_3960, recall_3964, recall_3967, recall_3969, recall_3971, recall_3973, recall_3976, recall_3977, recall_3980, recall_3981, recall_3983, recall_3984, recall_3989, recall_3990, recall_3991, recall_3992, recall_3993, recall_4002, recall_4006, recall_4007, recall_4008, recall_4010, recall_4011, recall_4012,recall_4013, recall_4014, recall_4017, recall_4019, recall_4021, recall_4024, recall_4025, recall_4026, recall_4027, recall_4028, recall_4030, recall_4034, recall_4038, recall_4039,recall_4046, recall_4048, recall_4049,recall_4051, recall_4052, recall_4053, recall_4055, recall_4056, recall_4057, recall_4059, recall_4063, recall_4068, recall_4071, recall_4074, recall_4076, recall_4078, recall_4079, recall_4080, recall_4081, recall_4089, recall_4090, recall_4092, recall_4093, recall_4094, recall_4096, recall_4097, recall_4098, recall_4101, recall_4102, recall_4103, recall_4104,recall_4106, recall_4108, recall_4109, recall_4115, recall_4116, recall_4119, recall_4122, recall_4124, recall_4126, recall_4127, recall_4129, recall_4130, recall_4132, recall_4135, recall_4137, recall_4138, recall_4140, recall_4141, recall_4147, recall_4148, recall_4149, recall_4151, recall_4154, recall_4156, recall_4159, recall_4160, recall_4165, recall_4166, recall_4169, recall_4171, recall_4173, recall_4175, recall_4176, recall_4177, recall_4179, recall_4180, recall_4182, recall_4183, recall_4185, recall_4186, recall_4187, recall_4192, recall_4193, recall_4194, recall_4196, recall_4202, recall_4206, recall_4211, recall_4213, recall_4216, recall_4217, recall_4219, recall_4220, recall_4222, recall_4224, recall_4225, recall_4229, recall_4230, recall_4238, recall_4239, recall_4242, recall_4153)



#list of task data 
sf11_by_sub_v2 <- list(split_enc_11_v2$`3878`, split_enc_11_v2$'3879', split_enc_11_v2$'3880', split_enc_11_v2$'3882', split_enc_11_v2$'3885', split_enc_11_v2$'3886', split_enc_11_v2$'3893', split_enc_11_v2$'3895', split_enc_11_v2$'3896', split_enc_11_v2$'3902', split_enc_11_v2$'3905', split_enc_11_v2$'3907', split_enc_11_v2$'3908', split_enc_11_v2$'3913', split_enc_11_v2$'3916', split_enc_11_v2$'3918', split_enc_11_v2$'3919', split_enc_11_v2$'3927', split_enc_11_v2$'3928', split_enc_11_v2$'3929', split_enc_11_v2$'3935', split_enc_11_v2$'3938', split_enc_11_v2$'3939', split_enc_11_v2$'3940', split_enc_11_v2$'3943', split_enc_11_v2$'3944', split_enc_11_v2$'3945', split_enc_11_v2$'3946', split_enc_11_v2$'3948', split_enc_11_v2$'3949', split_enc_11_v2$'3953', split_enc_11_v2$'3954', split_enc_11_v2$'3955', split_enc_11_v2$'3957', split_enc_11_v2$'3958', split_enc_11_v2$'3959', split_enc_11_v2$'3960', split_enc_11_v2$'3964', split_enc_11_v2$'3967', split_enc_11_v2$'3969', split_enc_11_v2$'3971', split_enc_11_v2$'3973', split_enc_11_v2$'3976', split_enc_11_v2$'3977', split_enc_11_v2$'3980', split_enc_11_v2$'3981', split_enc_11_v2$'3983', split_enc_11_v2$'3984', split_enc_11_v2$'3989', split_enc_11_v2$'3990', split_enc_11_v2$'3991', split_enc_11_v2$'3992', split_enc_11_v2$'3993', split_enc_11_v2$'4002', split_enc_11_v2$'4006', split_enc_11_v2$'4007', split_enc_11_v2$'4008', split_enc_11_v2$'4010',split_enc_11_v2$'4011', split_enc_11_v2$'4012',split_enc_11_v2$'4013', split_enc_11_v2$'4014', split_enc_11_v2$'4017', split_enc_11_v2$'4019', split_enc_11_v2$'4021', split_enc_11_v2$'4024', split_enc_11_v2$'4025', split_enc_11_v2$'4026', split_enc_11_v2$'4027', split_enc_11_v2$'4028', split_enc_11_v2$'4030', split_enc_11_v2$'4034', split_enc_11_v2$'4038', split_enc_11_v2$'4039', split_enc_11_v2$'4046', split_enc_11_v2$'4048', split_enc_11_v2$'4049', split_enc_11_v2$'4051', split_enc_11_v2$'4052', split_enc_11_v2$'4053', split_enc_11_v2$'4055', split_enc_11_v2$'4056', split_enc_11_v2$'4057', split_enc_11_v2$'4059', split_enc_11_v2$'4063', split_enc_11_v2$'4068', split_enc_11_v2$'4071', split_enc_11_v2$'4074', split_enc_11_v2$'4076', split_enc_11_v2$'4078', split_enc_11_v2$'4079', split_enc_11_v2$'4080', split_enc_11_v2$'4081', split_enc_11_v2$'4089', split_enc_11_v2$'4090', split_enc_11_v2$'4092', split_enc_11_v2$'4093', split_enc_11_v2$'4094',split_enc_11_v2$'4096', split_enc_11_v2$'4097', split_enc_11_v2$'4098', split_enc_11_v2$`4101`, split_enc_11_v2$`4102`,  split_enc_11_v2$`4103`, split_enc_11_v2$`4104`, split_enc_11_v2$`4106`, split_enc_11_v2$`4108`, split_enc_11_v2$`4109`, split_enc_11_v2$`4115`, split_enc_11_v2$`4116`, split_enc_11_v2$`4119`, split_enc_11_v2$`4122`, split_enc_11_v2$`4124`, split_enc_11_v2$`4126`, split_enc_11_v2$`4127`, split_enc_11_v2$`4129`, split_enc_11_v2$`4130`, split_enc_11_v2$`4132`, split_enc_11_v2$`4135`, split_enc_11_v2$'4137', split_enc_11_v2$'4138', split_enc_11_v2$'4140', split_enc_11_v2$'4141', split_enc_11_v2$'4147', split_enc_11_v2$'4148', split_enc_11_v2$'4149', split_enc_11_v2$'4151',split_enc_11_v2$'4154', split_enc_11_v2$'4156', split_enc_11_v2$'4159', split_enc_11_v2$'4160', split_enc_11_v2$'4165', split_enc_11_v2$'4166', split_enc_11_v2$'4169', split_enc_11_v2$'4171', split_enc_11_v2$'4173', split_enc_11_v2$'4175', split_enc_11_v2$'4176', split_enc_11_v2$'4177', split_enc_11_v2$'4179', split_enc_11_v2$'4180', split_enc_11_v2$'4182', split_enc_11_v2$'4183', split_enc_11_v2$'4185', split_enc_11_v2$'4186', split_enc_11_v2$'4187', split_enc_11_v2$'4192', split_enc_11_v2$'4193', split_enc_11_v2$'4194', split_enc_11_v2$'4196', split_enc_11_v2$'4202', split_enc_11_v2$'4206', split_enc_11_v2$'4211', split_enc_11_v2$'4213', split_enc_11_v2$'4216', split_enc_11_v2$'4217', split_enc_11_v2$'4219', split_enc_11_v2$'4220', split_enc_11_v2$'4222', split_enc_11_v2$'4224', split_enc_11_v2$'4225', split_enc_11_v2$'4229', split_enc_11_v2$'4230', split_enc_11_v2$'4238', split_enc_11_v2$'4239', split_enc_11_v2$'4242', split_enc_11_v2$'4153')

#for every subject:
c = 0 
for (ssid in array(1:length(recall11_df_immed_2))){
    i = sf11_by_sub_v2[[ssid]]
    j = recall11_df_immed_2[[ssid]]
    c = c +1 
    output  <- i %>% 
      mutate(recalls = tolower(word_enc) %in% tolower(j$V3))%>%  #matches the recall with task word
      mutate(recalls = case_when(recalls == "TRUE" ~ 1, #if recalled word, puts a 1 
                               recalls == "FALSE" ~ 0)) %>%  
      group_by(condition, trialcode) %>% 
      mutate(sum_recall = sum(recalls)) %>% # this column sums the recalls by condition and task
      group_by(blocknum) %>% 
      mutate(sum_recall_block = sum(recalls)) %>% #sums recalls by block
      group_by(trialcode) %>% 
      mutate(sum_recall_trialcode = sum(recalls)) #sums recalls just by task 
    if (c ==1) {
      sf11_total_v2 = output
    } else {
      sf11_total_v2 = rbind(sf11_total_v2,output)
    }}

sf11_total_v2 
                  



```


```{r}
#recall demographic - immediate 
library(dplyr)
detach(package:Rmisc) 
detach(package:plyr)


sf11_total_immed_2<- sf11_total_v2 %>% 
  group_by(subject) %>% 
  mutate(recall_percent2 = sum(recalls)/96*100) %>% 
  summarise(mean_rec = mean(recall_percent2, na.rm = TRUE))
sf11_total_immed_2


#plot of each subjects recall in order 
sf11_total_immed_2 %>% 
  ggplot(aes(x = reorder(as.character(subject), mean_rec), y = mean_rec))+
  geom_col(fill = "orchid", width = .8)+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 45,hjust = 1))+
  labs(title    = "Percent of Total Words Recalled",
         x        = "Subject Number",
         y        = "Percent Recalled")


mean_recall11_2<- mean(sf11_total_immed_2$mean_rec, na.rm = TRUE)
mean_recall11_2


sd_11_2 <-sd(sf11_total_immed_2$mean_rec, na.rm = TRUE)
```

```{r}
#compare means between same and novel 

sf11_total_v2_immed_between<- sf11_total_v2 %>% 
  group_by(subject, between_condition) %>% 
  mutate(recall_percent2 = sum(recalls)/96*100) %>% 
  summarise(mean_rec = mean(recall_percent2, na.rm = TRUE))
sf11_total_v2_immed_between

sf11_total_immed_2_same <- sf11_total_v2_immed_between %>% 
  filter(between_condition == "same")


mean_recall11_same2<- mean(sf11_total_immed_2_same$mean_rec, na.rm = TRUE)
mean_recall11_same2


sf11_total_immed_2_novel <- sf11_total_v2_immed_between %>% 
  filter(between_condition == "novel")

mean_recall11_novel2<- mean(sf11_total_immed_2_novel$mean_rec, na.rm = TRUE)
mean_recall11_novel2


t.test(sf11_total_immed_2_same$mean_rec, sf11_total_immed_2_novel$mean_rec)

cohensD(mean_rec~between_condition, sf11_total_v2_immed_between)
```










```{r}
#outliers at immed recall
sf11_total_immed_2 %>% 
  arrange(mean_rec)


sd_11_immed_2 <-sd(sf11_total_immed_2$mean_rec, na.rm = TRUE)

mean_recall11_immed2 <- mean(sf11_total_immed_2$mean_rec, na.rm = TRUE)

mean_recall11_immed2 + (2.5 * sd_11_immed_2) #93.45
mean_recall11_immed2 - (2.5 * sd_11_immed_2) #negative 


```


```{r}
#separate by between condition 

sf11_total_v2_same <- sf11_total_v2 %>% 
  filter(between_condition == "same")


sf11_total_v2_novel <- sf11_total_v2 %>% 
  filter(between_condition == "novel")

sf11_total_v2 <- sf11_total_v2 %>% 
mutate(condition_switch_noswitch = case_when(condition == "control" ~ "no switch",
                                         condition == "high" ~"switch",
                                         condition == "mid" ~"switch"))
```



```{r}
#removes primacy items - removing first two switches 

sf11_total_v2_high_same <- sf11_total_v2_same %>% 
  filter(condition == "high") %>% 
   filter(trialnum == "5"| trialnum == "6"|trialnum == "7"| trialnum == "8"| trialnum == "9"| trialnum == "10"| trialnum == "11"| trialnum == "12"| trialnum == "13"| trialnum == "14"| trialnum == "15"| trialnum == "16")
  
  

sf11_total_v2_low_same <- sf11_total_v2_same %>% 
  filter(condition == "mid") %>% 
   filter(trialnum == "9"| trialnum == "10"| trialnum == "11"| trialnum == "12"| trialnum == "13"| trialnum == "14"| trialnum == "15"| trialnum == "16")

sf11_total_v2_control <- sf11_total_v2_same %>% 
  filter(condition == "control")



sf11_total_v2_same <- rbind(sf11_total_v2_high_same,sf11_total_v2_low_same, sf11_total_v2_control) %>% 
  arrange(by = subject, blocknum)



sf11_total_v2_high_novel <- sf11_total_v2_novel %>% 
  filter(condition == "high") %>% 
   filter(trialnum == "5"| trialnum == "6"|trialnum == "7"| trialnum == "8"| trialnum == "9"| trialnum == "10"| trialnum == "11"| trialnum == "12"| trialnum == "13"| trialnum == "14"| trialnum == "15"| trialnum == "16")


 sf11_total_v2_low_novel <- sf11_total_v2_novel %>% 
  filter(condition == "mid") %>% 
   filter(trialnum == "9"| trialnum == "10"| trialnum == "11"| trialnum == "12"| trialnum == "13"| trialnum == "14"| trialnum == "15"| trialnum == "16") 
 
 

sf11_total_v2_control_novel <- sf11_total_v2_novel %>% 
  filter(condition == "control")



sf11_total_v2_novel <- rbind(sf11_total_v2_high_novel,sf11_total_v2_low_novel, sf11_total_v2_control_novel) %>% 
  arrange(by = subject, blocknum)
 
 
 

```






```{r}
#plot average recalls for task and condition

#separate control into high and mid paired 
#no switch items in the control 

#JUST same

#main plot chunk 
detach(package:Rmisc)
detach(package:plyr)


sf11_total_tally_same_immed2 <- sf11_total_v2_same %>% 
  group_by(subject, condition) %>% 
  tally() 
sf11_total_tally_same_immed2


sf11_total_same_v2 <- sf11_total_v2_same %>% 
  dplyr:: select(subject, condition, trialcode, sum_recall, recalls) %>% 
  group_by(subject, condition) %>% 
  mutate(sum_recall2 = sum(recalls)) %>% 
  summarise(mean_rec_cond = mean(sum_recall2)) 

merged_same2 <- merge(sf11_total_same_v2,sf11_total_tally_same_immed2)


merged_same2 <- merged_same2 %>% 
  mutate(prop_cond = mean_rec_cond/n)

merged_same2<- merged_same2 %>% 
  mutate(condition = fct_relevel(condition, "control", "mid", "high"))

library(Rmisc)



condition_same_immed2 <- summarySEwithin(merged_same2, measurevar="prop_cond", withinvars = c("condition"),idvar = "subject", na.rm=FALSE, conf.interval=.95)



condition_same_immed2 %>% 
  ggplot(aes(x = condition, y = prop_cond)) +
  geom_col(width = .7, aes(fill = condition), alpha = .8, color = "black", size = .3) +
  labs(title    = "Percentage of Recalls by Condition",
         x        = "Condition",
         y        = "Percent Recalled")+
  theme_classic()+
  geom_errorbar(width=.1, position=position_dodge(.9), aes(ymin=prop_cond-se, ymax=prop_cond+se))+
scale_y_continuous(labels = scales::percent_format(accuracy = 1L), expand = c(0,0))+
  scale_x_discrete(labels=c("control" = "Control","mid"= "Low Switch", "high" = "High Switch"))+
    scale_fill_manual(values = c("grey60", "green4", "darkorchid4"))
```




```{r}
#model for the just same condition 

model_condition_same_11_v2<- glmer(recalls~condition +list_half+blocknum_contin + (1|subject)+ (1|word_enc), family = binomial, data = sf11_total_v2_same)
summary(model_condition_same_11_v2)

sf11_total_v2_same<-sf11_total_v2_same %>% 
  mutate(condition = fct_relevel(condition, "mid", "control", "high"))

plot_model(model_condition_same_11_v2, type = "pred")
```


```{r}
#plot average recalls for task and condition

#separate control into high and mid paired 
#no switch items in the control 

#JUST novel

#main plot chunk 
detach(package:Rmisc)
detach(package:plyr)


sf12_total_tally_novel_immed2 <- sf11_total_v2_novel %>% 
  group_by(subject, condition) %>% 
  tally() 
sf12_total_tally_novel_immed2


sf12_total_novel_v2 <- sf11_total_v2_novel %>% 
  dplyr:: select(subject, condition, trialcode, sum_recall, recalls) %>% 
  group_by(subject, condition) %>% 
  mutate(sum_recall2 = sum(recalls)) %>% 
  summarise(mean_rec_cond = mean(sum_recall2)) 

merged_novel2 <- merge(sf12_total_novel_v2,sf12_total_tally_novel_immed2)


merged_novel2 <- merged_novel2 %>% 
  mutate(prop_cond = mean_rec_cond/n)

merged_novel2<- merged_novel2 %>% 
  mutate(condition = fct_relevel(condition, "control", "mid", "high"))

library(Rmisc)

condition_novel_immed2 <- summarySEwithin(merged_novel2, measurevar="prop_cond", withinvars = c("condition"),idvar = "subject", na.rm=FALSE, conf.interval=.95)



condition_novel_immed2 %>% 
  ggplot(aes(x = condition, y = prop_cond)) +
  geom_col(width = .7, aes(fill = condition), alpha = .8, color = "black", size = .3) +
  labs(title    = "Percentage of Recalls by Condition",
         x        = "Condition",
         y        = "Percent Recalled")+
  theme_classic()+
  geom_errorbar(width=.1, position=position_dodge(.9), aes(ymin=prop_cond-se, ymax=prop_cond+se))+
  scale_y_continuous(labels = scales::percent_format(accuracy = 1L), expand = c(0,0))+
  scale_x_discrete(labels=c("control" = "Control","mid"= "Low Switch", "high" = "High Switch"))+
    scale_fill_manual(values = c("grey60", "green4", "darkorchid4"))
```

```{r}
#model for the just novel condition 


sf11_total_v2_novel<- sf11_total_v2_novel %>% 
  mutate(condition = fct_relevel(condition, "high","mid", "control"))

model_condition_novel_11_v2<- glmer(recalls~condition +list_half+blocknum_contin + (1|subject)+ (1|word_enc), family = binomial, data = sf11_total_v2_novel)
summary(model_condition_novel_11_v2)

plot_model(model_condition_novel_11_v2, type = "pred")
```




```{r}
#plot same and novel together

between_condition_bind_immed_v2 <- rbind(condition_same_immed2, condition_novel_immed2)

between_condition_bind_immed_v2 <- between_condition_bind_immed_v2 %>% 
  mutate(between_condition = case_when(N == 83 ~"same",
                                       N == 84 ~ "novel"))


v2_immed_11 <- between_condition_bind_immed_v2 %>% 
  ggplot(aes(x = condition, fill = interaction(between_condition,condition), y = prop_cond)) +
  geom_bar(position="dodge", stat="identity", color = "black", size = .3, alpha = .8) +
  labs(title    = "Percentage of Recalls by Condition and Task",
         x        = "Condition",
         y        = "Percent Recalled")+
  theme_classic()+
  geom_errorbar(width=.1, position=position_dodge(.9), aes(ymin=prop_cond-se, ymax=prop_cond+se))+
  scale_y_continuous(labels = scales::percent_format(accuracy = 1L), expand = c(0,0))+
  scale_x_discrete(labels=c("control" = "Control","mid"= "Low Switch", "high" = "High Switch"))+
  scale_fill_manual(name = "Condition", values=c("grey60", "grey20", "darkseagreen2", "darkgreen", "lavender", "darkorchid4")) +
  facet_wrap(.~between_condition)




ggsave(plot=v2_immed_11, width = 8, height = 5, filename="~/v2_immed_11_2_new.pdf")
```


```{r}
#total model 

sf11_total_v2 <- rbind(sf11_total_v2_novel, sf11_total_v2_same)



model_condition_total_11_v2<- glmer(recalls~condition*between_condition +list_half+blocknum_contin + (1|subject)+ (1|word_enc), family = binomial, data = sf11_total_v2)
summary(model_condition_total_11_v2)


sf11_total_v2_high <- sf11_total_v2 %>% 
  filter(condition == "high"| condition == "control")


model_condition_total_11_v2_high<- glmer(recalls~condition*between_condition +list_half+blocknum_contin + (1|subject)+ (1|word_enc), family = binomial, data = sf11_total_v2_high)
summary(model_condition_total_11_v2_high)

```



```{r}
#boundary vs preboundary- supplemental materials 

detach(package:Rmisc)
detach(package:plyr)


sf11_total_v2_mid_spc_3<- sf11_total_v2 %>% 
  filter(condition == "mid") %>% 
  filter(trialnum == "5" | trialnum == "6" |trialnum == "8" |trialnum == "9" |trialnum == "10" |trialnum == "12") %>%
  mutate(trialnum_new = case_when(trialnum == "5" ~ "boundary",
                                  trialnum == "6" ~ "postboundary",
                               trialnum == "8" ~ "preboundary",
                               trialnum == "9" ~ "boundary",
                               trialnum == "10" ~ "postboundary",
                               trialnum == "12" ~ "preboundary")) 



spc_mid_v2_11_tally_immed2 <- sf11_total_v2_mid_spc_3 %>% 
  group_by(subject, trialnum_new) %>% 
  tally() 
spc_mid_v2_11_tally_immed2


spc_mid_v2_11_immed2 <- sf11_total_v2_mid_spc_3 %>% 
  dplyr:: select(subject, trialnum_new, between_condition, recalls) %>% 
  group_by(subject, trialnum_new, between_condition) %>% 
  mutate(sum_recall2 = sum(recalls)) %>% 
  summarise(mean_rec_cond = mean(sum_recall2)) 


merged_spc_immed2 <- merge(spc_mid_v2_11_immed2,spc_mid_v2_11_tally_immed2)


merged_spc_immed2 <- merged_spc_immed2 %>% 
  mutate(prop_cond = mean_rec_cond/n)


merged_spc_immed2<- merged_spc_immed2 %>% 
  mutate(trialnum_new = fct_relevel(trialnum_new, "preboundary", "boundary", "postboundary"))


library(Rmisc)

spc_mid_11_v2_immed2 <- summarySEwithin(merged_spc_immed2, measurevar="prop_cond", withinvars = c("trialnum_new", "between_condition"),idvar = "subject", na.rm=FALSE, conf.interval=.95)


v2_spc_sf11_bound_immed <- spc_mid_11_v2_immed2 %>% 
  ggplot(aes(x = trialnum_new, fill = interaction(between_condition,trialnum_new), y = prop_cond)) +
  geom_bar(position="dodge", stat="identity", color = "black", size = .3, alpha = .8) +
  labs(title    = "Percentage of Recalls by Condition and Task",
         x        = "Transition Type",
         y        = "Percent Recalled")+
  theme_classic()+
  geom_errorbar(width=.1, position=position_dodge(.9), aes(ymin=prop_cond-se, ymax=prop_cond+se))+
  scale_y_continuous(labels = scales::percent_format(accuracy = 1L), expand = c(0,0))+
  scale_fill_manual(name = "Transition Type", values=c("grey60", "grey20", "darkseagreen2", "darkgreen", "grey60", "grey20","lavender", "darkorchid4")) +
  facet_wrap(.~between_condition)

ggsave(plot=v2_spc_sf11_bound_immed, width = 8, height = 5, filename="~/v2_spc_sf11_bound_immed_se.pdf")
```


```{r}
#models 
sf11_total_v2_mid_spc_3<- sf11_total_v2_mid_spc_3 %>% 
  mutate(trialnum_new = fct_relevel(trialnum_new, "boundary", "preboundary", "postboundary"))


sf11_total_v2_mid_spc_3_cond <- sf11_total_v2_mid_spc_3 %>% 
  filter(between_condition == "novel")


sf11_total_v2_mid_spc_3_model_total<- glmer(recalls~trialnum_new+ blocknum_contin + (1|subject)+ (1|word_enc) + (1+latency), family = binomial, data = sf11_total_v2_mid_spc_3_cond)
summary(sf11_total_v2_mid_spc_3_model_total)

plot_model(sf11_total_v2_mid_spc_3_model_total, type = "pred")
```



```{r}
#serial position curve 
#same

#main plot chunk 
detach(package:Rmisc)
detach(package:plyr)


spc_tally_same <- sf11_total_v2_same %>% 
  group_by(subject, trialnum) %>% 
  tally() 
spc_tally_same


spc_plot_same <- sf11_total_v2_same %>% 
  dplyr:: select(subject, trialnum, recalls) %>% 
  group_by(subject, trialnum) %>% 
  mutate(sum_recall_spc = sum(recalls)) %>% 
  summarise(mean_rec_spc = mean(sum_recall_spc)) 

merged_spc_same <- merge(spc_plot_same,spc_tally_same)


merged_spc_same <- merged_spc_same %>% 
  mutate(prop_spc = mean_rec_spc/n)



library(Rmisc)

spc_within_same <- summarySEwithin(merged_spc_same, measurevar="prop_spc", withinvars= c("trialnum"), idvar="subject", na.rm=FALSE, conf.interval=.95)



spc_within_same %>% 
  ggplot(aes(x = trialnum, y = prop_spc)) +
  geom_point()+
  scale_y_continuous(labels = scales::percent_format(accuracy = 1L), expand = c(0,0))


```




```{r}
#prepare the data for temporal clustering by adding necessary columns to the recall dataframe 

add_columns <- function(recall_df, enc_df) {
  selected_enc_df <- enc_df[, c("condition", "trialcode", "subject", "blocknum", "list_half", "task_switch" ,"trialnum", "blockcode", "word_enc")]
  merged_df <- left_join(recall_df, selected_enc_df, by = c("V3" = "word_enc"))
  return(merged_df)
}

# Apply the function for each pair of recall and encoding data frames
merged_recall_list <- Map(add_columns, recall11_df_immed_2, sf11_by_sub_v2)

# Identify the common columns across all data frames
common_columns <- Reduce(intersect, lapply(merged_recall_list, colnames))

# Ensure that each data frame in the list contains only the common columns
cleaned_recall_list <- lapply(merged_recall_list, function(df) df[, common_columns])

# Combine the resulting data frames into one
recall11_df_immed_2_3 <- do.call("rbind", cleaned_recall_list)


```





```{r}
#set up for temporal clustering for MATLAB 

#encoding and retrieval for just blocks with mid in it 
#Same


sf11_by_sub_v2_2 <- do.call("rbind", sf11_by_sub_v2) #rebinds into one dataframe for analysis 

sf11_midblocks_same_v2 <- sf11_by_sub_v2_2 %>% 
  filter(blockcode == "mid_same" | blockcode == "mid_same2")


sf11_mid_samev2 <- split(sf11_midblocks_same_v2,sf11_midblocks_same_v2$subject)


encod_list_mid_same = list()
for (i in sf11_mid_samev2){
  encod_vert<- unstack(i, pool_number~blocknum)
  nrow <- max(sapply(encod_vert, length))
  encod_vert <- sapply(encod_vert, function(x) {
  length(x) <- 8
  x }) 
  encod_hor <- t(encod_vert) #transposes it 
  encod_list_mid_same[[length(encod_list_mid_same)+1]] = encod_hor}


names(encod_list_mid_same)  <- paste("mid_enc_same_", c(3879 ,3885, 3893 ,3895 ,3905 ,3907 ,3913 ,3919 ,3927 ,3929 ,3935 ,3939 ,3943 ,3945 ,3949 ,3953 ,3955 ,3957 ,3959 ,3967 ,3969 ,3971 ,3973 ,3977 ,3981 ,3983 ,3989 ,3991 ,3993 ,4007, 4011, 4013 ,4017 ,4019 ,4021 ,4025 ,4027 ,4039 ,4049 ,4051 ,4053 ,4055 ,4057 ,4059 ,4063 ,4071 ,4079 ,4081 ,4089 ,4093 ,4097, 4101 ,4103 ,4109 ,4115 ,4119 ,4127 ,4129 ,4135 ,4137 ,4141 ,4147 ,4149 ,4151, 4153 ,4159 ,4165 ,4169 ,4171 ,4173 ,4175 ,4177 ,4179 ,4183 ,4185 ,4187 ,4193 ,4211 ,4213 ,4217 ,4219 ,4225 ,4229), sep="")




encod_list_mid_same

library(MASS)

encode_list_same <- do.call(rbind, encod_list_mid_same)

write.matrix(encode_list_same, file="encode_list11_mid_same_v2_5.csv")


#######################
#recall for mid, same 

recall11_df_immed_mid_same2 <- recall11_df_immed_2_3 %>% 
  filter(blockcode == "mid_same" | blockcode == "mid_same2")
  

split_rec_mid11_same <- split(recall11_df_immed_mid_same2,recall11_df_immed_mid_same2$subject)



recall_list_mid_same = list()
for (i in split_rec_mid11_same){
  recall_vert<- unstack(i, V2~blocknum)
  recall_vert <- sapply(recall_vert, function(x) {
  length(x) <- 8
  x }) 
  recall_hor <- t(recall_vert) #transposes it 
  recall_hor[is.na(recall_hor)] <- 0
  recall_list_mid_same[[length(recall_list_mid_same)+1]] = recall_hor}




names(recall_list_mid_same)  <- paste("mid_rec_",  c(3879 ,3885, 3893 ,3895 ,3905 ,3907 ,3913 ,3919 ,3927 ,3929 ,3935 ,3939 ,3943 ,3945 ,3949 ,3953 ,3955 ,3957 ,3959 ,3967 ,3969 ,3971 ,3973 ,3977 ,3981 ,3983 ,3989 ,3991 ,3993 ,4007, 4011, 4013 ,4017 ,4019 ,4021 ,4025 ,4027 ,4039 ,4049 ,4051 ,4053 ,4055 ,4057 ,4059 ,4063 ,4071 ,4079 ,4081 ,4089 ,4093 ,4097, 4101 ,4103 ,4109 ,4115 ,4119 ,4127 ,4129 ,4135 ,4137 ,4141 ,4147 ,4149 ,4151, 4153 ,4159 ,4165 ,4169 ,4171 ,4173 ,4175 ,4177 ,4179 ,4183 ,4185 ,4187 ,4193 ,4211 ,4213 ,4217 ,4219 ,4225 ,4229), sep="")
recall_list_mid_same <- noquote(recall_list_mid_same)




recall_list <- do.call(rbind, recall_list_mid_same)




library(MASS)

write.matrix(recall_list, file="recall_list_11_mid_same_v2_5.csv")
```

```{r}
temp_clustering_mid_same_v2 <- c(0.5250,
    0.4238,
    0.5917,
    0.7133,
    0.4405,
    0.6060,
    0.3833,
    0.6950,
    0.6538,
    0.5963,
       NaN,
    0.7007,
    0.4167,
    0.2952,
    0.4967,
    0.3931,
    0.5667,
    0.5592,
    0.8296,
    0.5133,
    0.7133,
    0.6633,
    0.5417,
    0.5542,
    0.5617,
    0.4437,
    0.1833,
    0.6889,
    0.5000,
    0.3250,
    0.5250,
    0.5833,
    0.1750,
    0.8111,
    0.1667,
    0.6083,
    0.3889,
    0.9231,
    0.8444,
    0.6381,
    0.5500,
    0.6188,
    0.6398,
    0.6944,
    0.7562,
    0.8125,
    0.5056,
    0.5133,
    0.4900,
    0.6600,
    0.5083,
    0.6296,
    0.5107,
    0.8365,
    0.5095,
    0.3833,
    0.5427,
    0.4200,
    0.5760,
    0.9537,
    0.4826,
    0.2667,
    0.4733,
    0.7302,
    0.8549,
    0.5167,
    0.7500,
    0.8028,
    0.5833,
    0.3792,
    0.4750,
    0.5560,
    0.5333,
    0.6030,
    0.7812,
    0.5000,
    0.7852,
    0.7017,
    0.5417,
    0.5133,
    0.5181,
    0.5050,
    0.5583)

mean(temp_clustering_mid_same_v2, na.rm = TRUE)
sd(temp_clustering_mid_same_v2, na.rm = TRUE)/ sqrt(length(temp_clustering_mid_same_v2))


```



```{r}
#set up for temporal clustering for MATLAB 
#encoding and retrieval for just blocks with high in it 
#Same


sf11_by_sub_v2_2 <- do.call("rbind", sf11_by_sub_v2) #rebinds into one dataframe for analysis 

sf11_highblocks_same_v2 <- sf11_by_sub_v2_2 %>% 
  filter(blockcode == "high_same" | blockcode == "high_same2")


sf11_high_samev2 <- split(sf11_highblocks_same_v2,sf11_highblocks_same_v2$subject)


encod_list_high_same = list()
for (i in sf11_high_samev2){
  encod_vert<- unstack(i, pool_number~blocknum)
  nrow <- max(sapply(encod_vert, length))
  encod_vert <- sapply(encod_vert, function(x) {
  length(x) <- 12
  x }) 
  encod_hor <- t(encod_vert) #transposes it 
  encod_list_high_same[[length(encod_list_high_same)+1]] = encod_hor}


names(encod_list_high_same)  <- paste("high_enc_same_", c(3879 ,3885, 3893 ,3895 ,3905 ,3907 ,3913 ,3919 ,3927 ,3929 ,3935 ,3939 ,3943 ,3945 ,3949 ,3953 ,3955 ,3957 ,3959 ,3967 ,3969 ,3971 ,3973 ,3977 ,3981 ,3983 ,3989 ,3991 ,3993 ,4007, 4011,4013 ,4017 ,4019 ,4021 ,4025 ,4027 ,4039 ,4049 ,4051 ,4053 ,4055 ,4057 ,4059 ,4063 ,4071 ,4079 ,4081 ,4089 ,4093 ,4097, 4101 ,4103 ,4109 ,4115 ,4119 ,4127 ,4129 ,4135 ,4137 ,4141 ,4147 ,4149 ,4151,4153 ,4159 ,4165 ,4169 ,4171 ,4173 ,4175 ,4177 ,4179 ,4183 ,4185 ,4187 ,4193 ,4211 ,4213 ,4217 ,4219 ,4225 ,4229), sep="")




encod_list_high_same

library(MASS)

encode_list_same <- do.call(rbind, encod_list_high_same)

write.matrix(encode_list_same, file="encode_list11_high_same_v2_5.csv")


#######################
#recall for high, same 

recall11_df_immed_high_same2 <- recall11_df_immed_2_3 %>% 
  filter(blockcode == "high_same" | blockcode == "high_same2")
  

split_rec_high11_same <- split(recall11_df_immed_high_same2,recall11_df_immed_high_same2$subject)



recall_list_high_same = list()
for (i in split_rec_high11_same){
  recall_vert<- unstack(i, V2~blocknum)
  recall_vert <- sapply(recall_vert, function(x) {
  length(x) <- 12
  x }) 
  recall_hor <- t(recall_vert) #transposes it 
  recall_hor[is.na(recall_hor)] <- 0
  recall_list_high_same[[length(recall_list_high_same)+1]] = recall_hor}




names(recall_list_high_same)  <- paste("high_rec_",  c(3879 ,3885, 3893 ,3895 ,3905 ,3907 ,3913 ,3919 ,3927 ,3929 ,3935 ,3939 ,3943 ,3945 ,3949 ,3953 ,3955 ,3957 ,3959 ,3967 ,3969 ,3971 ,3973 ,3977 ,3981 ,3983 ,3989 ,3991 ,3993 ,4007, 4011,4013 ,4017 ,4019 ,4021 ,4025 ,4027 ,4039 ,4049 ,4051 ,4053 ,4055 ,4057 ,4059 ,4063 ,4071 ,4079 ,4081 ,4089 ,4093 ,4097, 4101 ,4103 ,4109 ,4115 ,4119 ,4127 ,4129 ,4135 ,4137 ,4141 ,4147 ,4149 ,4151,4153 ,4159 ,4165 ,4169 ,4171 ,4173 ,4175 ,4177 ,4179 ,4183 ,4185 ,4187 ,4193 ,4211 ,4213 ,4217 ,4219 ,4225 ,4229), sep="")
recall_list_high_same <- noquote(recall_list_high_same)




recall_list <- do.call(rbind, recall_list_high_same)




library(MASS)

write.matrix(recall_list, file="recall_list_11_high_same_v2_5.csv")
```

```{r}
temp_clustering_high_same_v2 <- c(0.5119,
    0.4890,
    0.5819,
    0.8629,
    0.7282,
    0.4430,
    0.7090,
    0.5335,
       NaN,
    0.4940,
    0.4431,
    0.6247,
    0.4341,
    0.5912,
    0.4710,
    0.5698,
    0.5401,
    0.6887,
    0.7167,
    0.5736,
    0.7277,
    0.5123,
    0.3643,
    0.4572,
    0.5697,
    0.5471,
    0.5437,
    0.4750,
    0.4602,
    0.4094,
    0.7433,
    0.3874,
    0.4791,
    0.5160,
    0.5736,
    0.6139,
    0.4600,
    0.9611,
    0.5412,
    0.5286,
    0.4272,
    0.5057,
    0.6356,
    0.5693,
    0.6592,
    0.4583,
    0.3486,
    0.1944,
    0.4247,
    0.4916,
    0.6449,
    0.7300,
    0.4714,
    0.4739,
    0.4573,
    0.6264,
    0.7814,
    0.4498,
    0.5086,
    0.9262,
    0.3988,
    0.6154,
    0.3736,
    0.6222,
    0.9380,
    0.6300,
    0.5822,
    0.5544,
    0.3069,
    0.5500,
    0.6907,
    0.6683,
    0.8083,
    0.5554,
    0.9500,
    0.3314,
    0.8079,
    0.4532,
    0.5969,
    0.2372,
    0.6358,
    0.4119,
    0.6077)

mean(temp_clustering_high_same_v2, na.rm = TRUE)
sd(temp_clustering_high_same_v2, na.rm = TRUE)/ sqrt(length(temp_clustering_high_same_v2))
```



```{r}
#Same total score 

temp_clustering_same_v2 <- c(0.5250,
    0.4238,
    0.5917,
    0.7133,
    0.4405,
    0.6060,
    0.3833,
    0.6950,
    0.6538,
    0.5963,
       NaN,
    0.7007,
    0.4167,
    0.2952,
    0.4967,
    0.3931,
    0.5667,
    0.5592,
    0.8296,
    0.5133,
    0.7133,
    0.6633,
    0.5417,
    0.5542,
    0.5617,
    0.4437,
    0.1833,
    0.6889,
    0.5000,
    0.3250,
    0.5250,
    0.5833,
    0.1750,
    0.8111,
    0.1667,
    0.6083,
    0.3889,
    0.9231,
    0.8444,
    0.6381,
    0.5500,
    0.6188,
    0.6398,
    0.6944,
    0.7562,
    0.8125,
    0.5056,
    0.5133,
    0.4900,
    0.6600,
    0.5083,
    0.6296,
    0.5107,
    0.8365,
    0.5095,
    0.3833,
    0.5427,
    0.4200,
    0.5760,
    0.9537,
    0.4826,
    0.2667,
    0.4733,
    0.7302,
    0.8549,
    0.5167,
    0.7500,
    0.8028,
    0.5833,
    0.3792,
    0.4750,
    0.5560,
    0.5333,
    0.6030,
    0.7812,
    0.5000,
    0.7852,
    0.7017,
    0.5417,
    0.5133,
    0.5181,
    0.5050,
    0.5583,
    0.5119,
    0.4890,
    0.5819,
    0.8629,
    0.7282,
    0.4430,
    0.7090,
    0.5335,
       NaN,
    0.4940,
    0.4431,
    0.6247,
    0.4341,
    0.5912,
    0.4710,
    0.5698,
    0.5401,
    0.6887,
    0.7167,
    0.5736,
    0.7277,
    0.5123,
    0.3643,
    0.4572,
    0.5697,
    0.5471,
    0.5437,
    0.4750,
    0.4602,
    0.4094,
    0.7433,
    0.3874,
    0.4791,
    0.5160,
    0.5736,
    0.6139,
    0.4600,
    0.9611,
    0.5412,
    0.5286,
    0.4272,
    0.5057,
    0.6356,
    0.5693,
    0.6592,
    0.4583,
    0.3486,
    0.1944,
    0.4247,
    0.4916,
    0.6449,
    0.7300,
    0.4714,
    0.4739,
    0.4573,
    0.6264,
    0.7814,
    0.4498,
    0.5086,
    0.9262,
    0.3988,
    0.6154,
    0.3736,
    0.6222,
    0.9380,
    0.6300,
    0.5822,
    0.5544,
    0.3069,
    0.5500,
    0.6907,
    0.6683,
    0.8083,
    0.5554,
    0.9500,
    0.3314,
    0.8079,
    0.4532,
    0.5969,
    0.2372,
    0.6358,
    0.4119,
    0.6077)

mean(temp_clustering_same_v2, na.rm = TRUE)
sd(temp_clustering_same_v2, na.rm = TRUE)/ sqrt(length(temp_clustering_same_v2))
```







```{r}
#set up for temporal clustering for MATLAB 

#encoding and retrieval for just blocks with control in it 
#Same


sf11_by_sub_v2_2 <- do.call("rbind", sf11_by_sub_v2) #rebinds into one dataframe for analysis 

sf11_controlblocks_same_v2 <- sf11_by_sub_v2_2 %>% 
  filter(blockcode == "control_same" | blockcode == "control_same2")


sf11_control_samev2 <- split(sf11_controlblocks_same_v2,sf11_controlblocks_same_v2$subject)


encod_list_control_same = list()
for (i in sf11_control_samev2){
  encod_vert<- unstack(i, pool_number~blocknum)
  nrow <- max(sapply(encod_vert, length))
  encod_vert <- sapply(encod_vert, function(x) {
  length(x) <- 16
  x }) 
  encod_hor <- t(encod_vert) #transposes it 
  encod_list_control_same[[length(encod_list_control_same)+1]] = encod_hor}


names(encod_list_control_same)  <- paste("control_enc_same_", c(3879 ,3885, 3893 ,3895 ,3905 ,3907 ,3913 ,3919 ,3927 ,3929 ,3935 ,3939 ,3943 ,3945 ,3949 ,3953 ,3955 ,3957 ,3959 ,3967 ,3969 ,3971 ,3973 ,3977 ,3981 ,3983 ,3989 ,3991 ,3993 ,4007, 4011,4013 ,4017 ,4019 ,4021 ,4025 ,4027 ,4039 ,4049 ,4051 ,4053 ,4055 ,4057 ,4059 ,4063 ,4071 ,4079 ,4081 ,4089 ,4093 ,4097, 4101 ,4103 ,4109 ,4115 ,4119 ,4127 ,4129 ,4135 ,4137 ,4141 ,4147 ,4149 ,4151,4153 ,4159 ,4165 ,4169 ,4171 ,4173 ,4175 ,4177 ,4179 ,4183 ,4185 ,4187 ,4193 ,4211 ,4213 ,4217 ,4219 ,4225 ,4229), sep="")




encod_list_control_same

library(MASS)

encode_list_same <- do.call(rbind, encod_list_control_same)

write.matrix(encode_list_same, file="encode_list11_control_same_v2_4.csv")


#######################
#recall for control, same 

recall11_df_immed_control_same2 <- recall11_df_immed_2_3 %>% 
  filter(blockcode == "control_same" | blockcode == "control_same2")

  

split_rec_control11_same <- split(recall11_df_immed_control_same2,recall11_df_immed_control_same2$subject)



recall_list_control_same = list()
for (i in split_rec_control11_same){
  recall_vert<- unstack(i, V2~blocknum)
  recall_vert <- sapply(recall_vert, function(x) {
  length(x) <- 16
  x }) 
  recall_hor <- t(recall_vert) #transposes it 
  recall_hor[is.na(recall_hor)] <- 0
  recall_list_control_same[[length(recall_list_control_same)+1]] = recall_hor}




names(recall_list_control_same)  <- paste("control_rec_",  c(3879 ,3885, 3893 ,3895 ,3905 ,3907 ,3913 ,3919 ,3927 ,3929 ,3935 ,3939 ,3943 ,3945 ,3949 ,3953 ,3955 ,3957 ,3959 ,3967 ,3969 ,3971 ,3973 ,3977 ,3981 ,3983 ,3989 ,3991 ,3993 ,4007, 4011,4013 ,4017 ,4019 ,4021 ,4025 ,4027 ,4039 ,4049 ,4051 ,4053 ,4055 ,4057 ,4059 ,4063 ,4071 ,4079 ,4081 ,4089 ,4093 ,4097, 4101 ,4103 ,4109 ,4115 ,4119 ,4127 ,4129 ,4135 ,4137 ,4141 ,4147 ,4149 ,4151,4153 ,4159 ,4165 ,4169 ,4171 ,4173 ,4175 ,4177 ,4179 ,4183 ,4185 ,4187 ,4193 ,4211 ,4213 ,4217 ,4219 ,4225 ,4229), sep="")
recall_list_control_same <- noquote(recall_list_control_same)




recall_list <- do.call(rbind, recall_list_control_same)




library(MASS)

write.matrix(recall_list, file="recall_list_11_control_same_v2_4.csv")

```



```{r}
temp_clustering_control_same_v2 <- c( 0.6070,
    0.5659,
    0.5815,
    0.9108,
    0.6772,
    0.5104,
    0.5373,
    0.5580,
    0.5460,
    0.6068,
    0.4664,
    0.7139,
    0.6839,
    0.6916,
    0.5479,
    0.5718,
    0.6396,
    0.7286,
    0.6328,
    0.6629,
    0.8313,
    0.6470,
    0.5837,
    0.5040,
    0.5203,
    0.7916,
    0.7048,
    0.2390,
    0.6188,
    0.6050,
    0.7298,
    0.5053,
    0.4729,
    0.7206,
    0.3734,
    0.6885,
    0.7412,
    0.9653,
    0.5613,
    0.6297,
    0.6166,
    0.5598,
    0.7604,
    0.4922,
    0.5190,
    0.5798,
    0.5285,
    0.5889,
    0.6896,
    0.7003,
    0.5383,
    0.6541,
    0.6593,
    0.4765,
    0.5394,
    0.5050,
    0.7464,
    0.6171,
    0.5550,
    0.8640,
    0.5020,
    0.5093,
    0.5399,
    0.7859,
    0.9633,
    0.3924,
    0.5870,
    0.4849,
    0.4681,
    0.8214,
    0.7293,
    0.4754,
    0.6256,
    0.8074,
    0.9643,
    0.4836,
    0.8193,
    0.5491,
    0.5349,
    0.6666,
    0.6221,
    0.5973,
    0.5692)


mean(temp_clustering_control_same_v2, na.rm = TRUE)
sd(temp_clustering_control_same_v2, na.rm = TRUE)/ sqrt(length(temp_clustering_control_same_v2))
```


```{r}
#set up for temporal clustering for MATLAB 

#encoding and retrieval for just blocks with mid in it 
#novel


sf11_by_sub_v2_2 <- do.call("rbind", sf11_by_sub_v2) #rebinds into one dataframe for analysis 

sf11_midblocks_novel_v2 <- sf11_by_sub_v2_2 %>% 
  filter(blockcode == "mid_novel" | blockcode == "mid_novel2")


sf11_mid_novelv2 <- split(sf11_midblocks_novel_v2,sf11_midblocks_novel_v2$subject)


encod_list_mid_novel = list()
for (i in sf11_mid_novelv2){
  encod_vert<- unstack(i, pool_number~blocknum)
  nrow <- max(sapply(encod_vert, length))
  encod_vert <- sapply(encod_vert, function(x) {
  length(x) <- 8
  x }) 
  encod_hor <- t(encod_vert) #transposes it 
  encod_list_mid_novel[[length(encod_list_mid_novel)+1]] = encod_hor}


names(encod_list_mid_novel)  <- paste("mid_enc_novel_", c(3878 ,3880 ,3882 ,3886 ,3896 ,3902 ,3908 ,3916 ,3918 ,3928 ,3938 ,3940 ,3944 ,3946 ,3948 ,3954 ,3958 ,3960 ,3964 ,3976 ,3980 ,3984 ,3990 ,3992 ,4002 ,4006 ,4008 ,4010 ,4012 ,4014 ,4024 ,4026 ,4028 ,4030 ,4034 ,4038 ,4046 ,4048 ,4052 ,4056 ,4068 ,4074 ,4076 ,4078 ,4080 ,4090 ,4092,4094 ,4096 ,4098 ,4102 ,4104 ,4106 ,4108 ,4116 ,4122 ,4124 ,4126 ,4130 ,4132 ,4138 ,4140 ,4148 ,4154 ,4156 ,4160 ,4166 ,4176 ,4180 ,4182 ,4186 ,4192 ,4194 ,4196 ,4202 ,4206 ,4216 ,4220 ,4222 ,4224 ,4230 ,4238 ,4239, 4242), sep="")





encod_list_mid_novel

library(MASS)

encode_list_novel <- do.call(rbind, encod_list_mid_novel)

write.matrix(encode_list_novel, file="encode_list11_mid_novel_v2_4.csv")


#######################
#recall for mid, novel 

recall11_df_immed_mid_novel2 <- recall11_df_immed_2_3 %>% 
  filter(blockcode == "mid_novel" | blockcode == "mid_novel2")
  

split_rec_mid11_novel <- split(recall11_df_immed_mid_novel2,recall11_df_immed_mid_novel2$subject)



recall_list_mid_novel = list()
for (i in split_rec_mid11_novel){
  recall_vert<- unstack(i, V2~blocknum)
  recall_vert <- sapply(recall_vert, function(x) {
  length(x) <- 8
  x }) 
  recall_hor <- t(recall_vert) #transposes it 
  recall_hor[is.na(recall_hor)] <- 0
  recall_list_mid_novel[[length(recall_list_mid_novel)+1]] = recall_hor}




names(recall_list_mid_novel)  <- paste("mid_rec_",  c(3878 ,3880 ,3882 ,3886 ,3896 ,3902 ,3908 ,3916 ,3918 ,3928 ,3938 ,3940 ,3944 ,3946 ,3948 ,3954 ,3958 ,3960 ,3964 ,3976 ,3980 ,3984 ,3990 ,3992 ,4002 ,4006 ,4008 ,4010 ,4012 ,4014 ,4024 ,4026 ,4028 ,4030 ,4034 ,4038 ,4046 ,4048 ,4052 ,4056 ,4068 ,4074 ,4076 ,4078 ,4080 ,4090 ,4092,4094 ,4096 ,4098 ,4102 ,4104 ,4106 ,4108 ,4116 ,4122 ,4124 ,4126 ,4130 ,4132 ,4138 ,4140 ,4148 ,4154 ,4156 ,4160 ,4166 ,4176 ,4180 ,4182 ,4186 ,4192 ,4194 ,4196 ,4202 ,4206 ,4216 ,4220 ,4222 ,4224 ,4230 ,4238 ,4239, 4242), sep="")
recall_list_mid_novel <- noquote(recall_list_mid_novel)




recall_list <- do.call(rbind, recall_list_mid_novel)




library(MASS)

write.matrix(recall_list, file="recall_list_11_mid_novel_v2_4.csv")
```

```{r}
temp_clustering_mid_novel_v2 <- c(0.9167,
    0.4167,
    0.4688,
    0.3028,
    0.5977,
    0.5600,
    0.1958,
    0.6792,
    0.6524,
    0.6286,
    0.6515,
       NaN,
    0.6667,
    0.7979,
    0.4833,
    0.4591,
    0.9167,
    0.5889,
    0.4568,
    0.3861,
    0.6361,
    0.4833,
    0.7533,
         0,
    0.4792,
    0.9167,
    0.3389,
    0.7424,
    0.5492,
    0.5985,
    0.7226,
    0.5595,
    0.4917,
    0.5833,
    0.6917,
    0.7217,
    0.4806,
    0.7000,
    0.6643,
    0.6365,
    0.4417,
    0.9167,
    0.2917,
    0.9167,
    0.6562,
    0.5200,
    0.9167,
    0.5773,
    0.4869,
    0.5052,
    0.7500,
    0.6500,
    0.6800,
    0.5083,
    0.6357,
    0.9583,
    0.5778,
    0.6650,
    0.5972,
    0.6889,
    0.7514,
    0.9458,
    0.9729,
    0.7208,
    0.4375,
    0.8108,
    0.4667,
       NaN,
    0.6094,
    0.5861,
    0.7333,
    0.4283,
    0.5972,
    0.5667,
    0.6583,
    0.5417,
    0.6976,
    1.0000,
    0.6833,
    0.6988,
    0.8083,
    0.6667,
    0.5000,
    0.7315)

mean(temp_clustering_mid_novel_v2, na.rm = TRUE)
sd(temp_clustering_mid_novel_v2, na.rm = TRUE)/ sqrt(length(temp_clustering_mid_novel_v2))
```


```{r}
#set up for temporal clustering for MATLAB 

#encoding and retrieval for just blocks with high in it 
#novel


sf11_by_sub_v2_2 <- do.call("rbind", sf11_by_sub_v2) #rebinds into one dataframe for analysis 

sf11_highblocks_novel_v2 <- sf11_by_sub_v2_2 %>% 
  filter(blockcode == "high_novel" | blockcode == "high_novel2")


sf11_high_novelv2 <- split(sf11_highblocks_novel_v2,sf11_highblocks_novel_v2$subject)


encod_list_high_novel = list()
for (i in sf11_high_novelv2){
  encod_vert<- unstack(i, pool_number~blocknum)
  nrow <- max(sapply(encod_vert, length))
  encod_vert <- sapply(encod_vert, function(x) {
  length(x) <- 12
  x }) 
  encod_hor <- t(encod_vert) #transposes it 
  encod_list_high_novel[[length(encod_list_high_novel)+1]] = encod_hor}


names(encod_list_high_novel)  <- paste("high_enc_novel_", c(3878 ,3880 ,3882 ,3886 ,3896 ,3902 ,3908 ,3916 ,3918 ,3928 ,3938 ,3940 ,3944 ,3946 ,3948 ,3954 ,3958 ,3960 ,3964 ,3976 ,3980 ,3984 ,3990 ,3992 ,4002 ,4006 ,4008 ,4010 ,4012 ,4014 ,4024 ,4026 ,4028 ,4030 ,4034 ,4038 ,4046 ,4048 ,4052 ,4056 ,4068 ,4074 ,4076 ,4078 ,4080 ,4090 ,4092,4094 ,4096 ,4098 ,4102 ,4104 ,4106 ,4108 ,4116 ,4122 ,4124 ,4126 ,4130 ,4132 ,4138 ,4140 ,4148 ,4154 ,4156 ,4160 ,4166 ,4176 ,4180 ,4182 ,4186 ,4192 ,4194 ,4196 ,4202 ,4206 ,4216 ,4220 ,4222 ,4224 ,4230 ,4238 ,4239, 4242), sep="")




encod_list_high_novel

library(MASS)

encode_list_novel <- do.call(rbind, encod_list_high_novel)

write.matrix(encode_list_novel, file="encode_list11_high_novel_v2_4.csv")


#######################
#recall for high, novel 

recall11_df_immed_high_novel2 <- recall11_df_immed_2_3 %>% 
  filter(blockcode == "high_novel" | blockcode == "high_novel2")
  

split_rec_high11_novel <- split(recall11_df_immed_high_novel2,recall11_df_immed_high_novel2$subject)



recall_list_high_novel = list()
for (i in split_rec_high11_novel){
  recall_vert<- unstack(i, V2~blocknum)
  recall_vert <- sapply(recall_vert, function(x) {
  length(x) <- 12
  x }) 
  recall_hor <- t(recall_vert) #transposes it 
  recall_hor[is.na(recall_hor)] <- 0
  recall_list_high_novel[[length(recall_list_high_novel)+1]] = recall_hor}




names(recall_list_high_novel)  <- paste("high_rec_",  c(3878 ,3880 ,3882 ,3886 ,3896 ,3902 ,3908 ,3916 ,3918 ,3928 ,3938 ,3940 ,3944 ,3946 ,3948 ,3954 ,3958 ,3960 ,3964 ,3976 ,3980 ,3984 ,3990 ,3992 ,4002 ,4006 ,4008 ,4010 ,4012 ,4014 ,4024 ,4026 ,4028 ,4030 ,4034 ,4038 ,4046 ,4048 ,4052 ,4056 ,4068 ,4074 ,4076 ,4078 ,4080 ,4090 ,4092,4094 ,4096 ,4098 ,4102 ,4104 ,4106 ,4108 ,4116 ,4122 ,4124 ,4126 ,4130 ,4132 ,4138 ,4140 ,4148 ,4154 ,4156 ,4160 ,4166 ,4176 ,4180 ,4182 ,4186 ,4192 ,4194 ,4196 ,4202 ,4206 ,4216 ,4220 ,4222 ,4224 ,4230 ,4238 ,4239, 4242), sep="")
recall_list_high_novel <- noquote(recall_list_high_novel)




recall_list <- do.call(rbind, recall_list_high_novel)




library(MASS)

write.matrix(recall_list, file="recall_list_11_high_novel_v2_4.csv")
```

```{r}
temp_clustering_high_novel_v2 <- c( 0.5000,
    0.6486,
    0.6551,
    0.1333,
    0.5444,
    0.6655,
    0.7056,
    0.6976,
    0.6379,
    0.6237,
    0.7070,
    0.7111,
    0.7315,
       NaN,
    0.6644,
    0.5783,
    0.7477,
    0.3672,
    0.6340,
    0.4505,
    0.6244,
    0.3009,
    0.4703,
    0.5897,
    0.6452,
    0.5808,
    0.6037,
    0.8172,
    0.4690,
    0.7750,
    0.3635,
    0.5317,
    0.6625,
    0.3719,
    0.6088,
    0.6393,
    0.5694,
    0.7250,
    0.5995,
    0.5908,
    0.6999,
    0.7688,
    0.7287,
    0.5753,
    0.7222,
    0.6039,
    0.9500,
    0.5125,
    0.6180,
    0.7815,
    0.4333,
    0.6149,
    0.4798,
    0.6886,
    0.3500,
    0.6325,
    0.6152,
    0.3993,
    0.4853,
    0.6267,
    0.7813,
    0.8676,
    0.9077,
    0.7705,
    0.6586,
    0.5639,
    0.3922,
    0.2000,
    0.5385,
    0.5295,
    0.5751,
    0.5492,
    0.5718,
    0.3708,
    0.4938,
    0.6562,
    0.5746,
    0.4095,
    0.4042,
    0.6188,
    0.4667,
    0.4921,
    0.6774,
    0.6042)

mean(temp_clustering_high_novel_v2, na.rm = TRUE)
sd(temp_clustering_high_novel_v2, na.rm = TRUE)/ sqrt(length(temp_clustering_high_novel_v2))
```


```{r}
temp_clustering_novel_v2 <- c(0.9167,
    0.4167,
    0.4688,
    0.3028,
    0.5977,
    0.5600,
    0.1958,
    0.6792,
    0.6524,
    0.6286,
    0.6515,
       NaN,
    0.6667,
    0.7979,
    0.4833,
    0.4591,
    0.9167,
    0.5889,
    0.4568,
    0.3861,
    0.6361,
    0.4833,
    0.7533,
         0,
    0.4792,
    0.9167,
    0.3389,
    0.7424,
    0.5492,
    0.5985,
    0.7226,
    0.5595,
    0.4917,
    0.5833,
    0.6917,
    0.7217,
    0.4806,
    0.7000,
    0.6643,
    0.6365,
    0.4417,
    0.9167,
    0.2917,
    0.9167,
    0.6562,
    0.5200,
    0.9167,
    0.5773,
    0.4869,
    0.5052,
    0.7500,
    0.6500,
    0.6800,
    0.5083,
    0.6357,
    0.9583,
    0.5778,
    0.6650,
    0.5972,
    0.6889,
    0.7514,
    0.9458,
    0.9729,
    0.7208,
    0.4375,
    0.8108,
    0.4667,
       NaN,
    0.6094,
    0.5861,
    0.7333,
    0.4283,
    0.5972,
    0.5667,
    0.6583,
    0.5417,
    0.6976,
    1.0000,
    0.6833,
    0.6988,
    0.8083,
    0.6667,
    0.5000,
    0.7315,
    0.5000,
    0.6486,
    0.6551,
    0.1333,
    0.5444,
    0.6655,
    0.7056,
    0.6976,
    0.6379,
    0.6237,
    0.7070,
    0.7111,
    0.7315,
       NaN,
    0.6644,
    0.5783,
    0.7477,
    0.3672,
    0.6340,
    0.4505,
    0.6244,
    0.3009,
    0.4703,
    0.5897,
    0.6452,
    0.5808,
    0.6037,
    0.8172,
    0.4690,
    0.7750,
    0.3635,
    0.5317,
    0.6625,
    0.3719,
    0.6088,
    0.6393,
    0.5694,
    0.7250,
    0.5995,
    0.5908,
    0.6999,
    0.7688,
    0.7287,
    0.5753,
    0.7222,
    0.6039,
    0.9500,
    0.5125,
    0.6180,
    0.7815,
    0.4333,
    0.6149,
    0.4798,
    0.6886,
    0.3500,
    0.6325,
    0.6152,
    0.3993,
    0.4853,
    0.6267,
    0.7813,
    0.8676,
    0.9077,
    0.7705,
    0.6586,
    0.5639,
    0.3922,
    0.2000,
    0.5385,
    0.5295,
    0.5751,
    0.5492,
    0.5718,
    0.3708,
    0.4938,
    0.6562,
    0.5746,
    0.4095,
    0.4042,
    0.6188,
    0.4667,
    0.4921,
    0.6774,
    0.6042)

mean(temp_clustering_novel_v2, na.rm = TRUE)
sd(temp_clustering_novel_v2, na.rm = TRUE)/ sqrt(length(temp_clustering_novel_v2))
```



```{r}
#set up for temporal clustering for MATLAB 

#encoding and retrieval for just blocks with control in it 
#novel


sf11_by_sub_v2_2 <- do.call("rbind", sf11_by_sub_v2) #rebinds into one dataframe for analysis 

sf11_controlblocks_novel_v2 <- sf11_by_sub_v2_2 %>% 
  filter(blockcode == "control_novel" | blockcode == "control_novel2")


sf11_control_novelv2 <- split(sf11_controlblocks_novel_v2,sf11_controlblocks_novel_v2$subject)


encod_list_control_novel = list()
for (i in sf11_control_novelv2){
  encod_vert<- unstack(i, pool_number~blocknum)
  nrow <- max(sapply(encod_vert, length))
  encod_vert <- sapply(encod_vert, function(x) {
  length(x) <- 16
  x }) 
  encod_hor <- t(encod_vert) #transposes it 
  encod_list_control_novel[[length(encod_list_control_novel)+1]] = encod_hor}


names(encod_list_control_novel)  <- paste("control_enc_novel_", c(3878 ,3880 ,3882 ,3886 ,3896 ,3902 ,3908 ,3916 ,3918 ,3928 ,3938 ,3940 ,3944 ,3946 ,3948 ,3954 ,3958 ,3960 ,3964 ,3976 ,3980 ,3984 ,3990 ,3992 ,4002 ,4006 ,4008 ,4010 ,4012 ,4014 ,4024 ,4026 ,4028 ,4030 ,4034 ,4038 ,4046 ,4048 ,4052 ,4056 ,4068 ,4074 ,4076 ,4078 ,4080 ,4090 ,4092,4094 ,4096 ,4098 ,4102 ,4104 ,4106 ,4108 ,4116 ,4122 ,4124 ,4126 ,4130 ,4132 ,4138 ,4140 ,4148 ,4154 ,4156 ,4160 ,4166 ,4176 ,4180 ,4182 ,4186 ,4192 ,4194 ,4196 ,4202 ,4206 ,4216 ,4220 ,4222 ,4224 ,4230 ,4238 ,4239, 4242), sep="")




encod_list_control_novel

library(MASS)

encode_list_novel <- do.call(rbind, encod_list_control_novel)

write.matrix(encode_list_novel, file="encode_list11_control_novel_v2_3.csv")


#######################
#recall for control, novel 

recall11_df_immed_control_novel2 <- recall11_df_immed_2_3 %>% 
  filter(blockcode == "control_novel" | blockcode == "control_novel2")
  

split_rec_control11_novel <- split(recall11_df_immed_control_novel2,recall11_df_immed_control_novel2$subject)



recall_list_control_novel = list()
for (i in split_rec_control11_novel){
  recall_vert<- unstack(i, V2~blocknum)
  recall_vert <- sapply(recall_vert, function(x) {
  length(x) <- 16
  x }) 
  recall_hor <- t(recall_vert) #transposes it 
  recall_hor[is.na(recall_hor)] <- 0
  recall_list_control_novel[[length(recall_list_control_novel)+1]] = recall_hor}




names(recall_list_control_novel)  <- paste("control_rec_",  c(3878 ,3880 ,3882 ,3886 ,3896 ,3902 ,3908 ,3916 ,3918 ,3928 ,3938 ,3940 ,3944 ,3946 ,3948 ,3954 ,3958 ,3960 ,3964 ,3976 ,3980 ,3984 ,3990 ,3992 ,4002 ,4006 ,4008 ,4010 ,4012 ,4014 ,4024 ,4026 ,4028 ,4030 ,4034 ,4038 ,4046 ,4048 ,4052 ,4056 ,4068 ,4074 ,4076 ,4078 ,4080 ,4090 ,4092,4094 ,4096 ,4098 ,4102 ,4104 ,4106 ,4108 ,4116 ,4122 ,4124 ,4126 ,4130 ,4132 ,4138 ,4140 ,4148 ,4154 ,4156 ,4160 ,4166 ,4176 ,4180 ,4182 ,4186 ,4192 ,4194 ,4196 ,4202 ,4206 ,4216 ,4220 ,4222 ,4224 ,4230 ,4238 ,4239, 4242), sep="")
recall_list_control_novel <- noquote(recall_list_control_novel)




recall_list <- do.call(rbind, recall_list_control_novel)




library(MASS)

write.matrix(recall_list, file="recall_list_11_control_novel_v2_3.csv")
```


```{r}
temp_clustering_control_novel_v2 <- c(0.5710,
    0.4340,
    0.7179,
    0.7294,
    0.6481,
    0.3016,
    0.6425,
    0.7635,
    0.4382,
    0.4215,
    0.6695,
    0.6252,
    0.6936,
    0.7514,
    0.5004,
    0.6761,
    0.6370,
    0.6069,
    0.6259,
    0.5096,
    0.5675,
    0.5570,
    0.5422,
    0.6693,
    0.5875,
    0.3984,
    0.5735,
    0.6497,
    0.5264,
    0.5790,
    0.4886,
    0.6571,
    0.6505,
    0.5046,
    0.7618,
    0.3895,
    0.5361,
    0.3598,
    0.4053,
    0.6429,
    0.8305,
    0.7595,
    0.7465,
    0.8136,
    0.5380,
    0.6119,
    0.6250,
    0.7370,
    0.5304,
    0.6787,
    0.5499,
    0.7079,
    0.5998,
    0.4721,
    0.6982,
    0.3687,
    0.6228,
    0.6888,
    0.5552,
    0.5294,
    0.7928,
    0.9568,
    0.9884,
    0.6822,
    0.5677,
    0.5984,
    0.5963,
    0.7756,
    0.6495,
    0.5676,
    0.6249,
    0.5029,
    0.6735,
    0.6288,
    0.6670,
    0.6467,
    0.7263,
    0.7628,
    0.8731,
    0.8206,
    0.7141,
    0.6387,
    0.5200,
    0.7168)


mean(temp_clustering_control_novel_v2, na.rm = TRUE)
sd(temp_clustering_control_novel_v2, na.rm = TRUE)/ sqrt(length(temp_clustering_control_novel_v2))
```

```{r}
#greater than chance-level clust 

t.test(temp_clustering_high_novel_v2, mu = .5)

t.test(temp_clustering_high_same_v2, mu = .5)

t.test(temp_clustering_mid_novel_v2, mu = .5)

t.test(temp_clustering_mid_same_v2, mu = .5)


t.test(temp_clustering_control_same_v2, mu = .5)

t.test(temp_clustering_control_novel_v2, mu = .5)
```







```{r}
#compare 

t.test(temp_clustering_high_novel_v2, temp_clustering_high_same_v2)



t.test(temp_clustering_mid_novel_v2, temp_clustering_mid_same_v2)
#participants recalled  more items in order during the mid condition in the novel condition than in the mid condition in the switch back condition 


t.test(temp_clustering_high_same_v2, temp_clustering_mid_same_v2)


t.test(temp_clustering_mid_novel_v2, temp_clustering_high_novel_v2)


t.test(temp_clustering_control_same_v2, temp_clustering_control_novel_v2)

t.test(temp_clustering_same_v2, temp_clustering_novel_v2)

```




```{r}
#for plotting 
detach(package:Rmisc)
detach(package:plyr)


temp_clust_11v2 <- import("temp_clustering_sf11_v2_newcoding.csv")


temp_clust_11v2_2 <- temp_clust_11v2 %>% 
  group_by(condition, between_condition, subject) %>% 
  summarise(mean_temp_clust = mean(temp_clust_score)) 
 
  
temp_clust_11v2<- temp_clust_11v2 %>%   
   na.omit()



library(Rmisc)


temp_clust_sf11 <- summarySE(temp_clust_11v2, measurevar="temp_clust_score", groupvars = c("condition", "between_condition"), na.rm=FALSE, conf.interval=.95)

temp_clust_sf11<- temp_clust_sf11 %>% 
  mutate(condition = fct_relevel(condition, "control", "low", "high"))


library(scales)
v2_clust_11 <- temp_clust_sf11 %>% 
  ggplot(aes(x = condition, fill = interaction(between_condition,condition), y = temp_clust_score)) +
  geom_bar(position="dodge", stat="identity", color = "black", size = .3, alpha = .8) +
  labs(title    = "Temporal Clustering",
         x        = "Condition",
         y        = "Temporal Clustering Score")+
  theme_classic()+
  geom_errorbar(width=.1, position=position_dodge(.9), aes(ymin=temp_clust_score-se, ymax=temp_clust_score+se))+
  scale_y_continuous(expand = c(0,0))+
  coord_cartesian(ylim = c(.5, .7))+
  scale_x_discrete(labels=c("cont_mid" = "Control (Low)","mid"= "Low Switch", "cont_high" = "Control (High)", "high" = "High Switch"))+
  scale_fill_manual(name = "Condition", values=c("grey60", "grey20", "darkseagreen2", "darkgreen", "grey60", "grey20","lavender", "darkorchid4")) +
  facet_wrap(.~between_condition)


ggsave(plot=v2_clust_11, width = 8, height = 5, filename="~/v2_clust_11_se_2.pdf")




```




```{r}
#models 
recall_tempclust2 <- merge(corr_indiv_wm2, temp_clust_11v2)

recall_tempclust_formodel <- merge(sf11_total_v2, temp_clust_11v2_new)


temp_clust_11v2_new <- temp_clust_11v2 %>% 
  mutate(condition = case_when(condition == "low"~"mid",
                               condition == "high"~"high",
                               condition == "control"~"control"))


recall_tempclust_formodel_cond <- recall_tempclust_formodel %>% 
  filter(between_condition == "novel")

recall_tempclust_formodel_cond<- recall_tempclust_formodel_cond %>% 
  mutate(condition = fct_relevel(condition, "mid", "control", "high"))

recall_tempclust_model<- glmer(recalls~temp_clust_score*condition +blocknum_contin +list_half+ (1|subject)+ (1|word_enc), family = binomial, data = recall_tempclust_formodel_cond)
summary(recall_tempclust_model)

plot_model(recall_tempclust_model, type = "int")


recall_tempclust_low_same <- recall_tempclust %>% 
  filter(condition == "low") %>% 
  filter(between_condition == "same")


cor.test(recall_tempclust_low_same$mean_rec, recall_tempclust_low_same$temp_clust_score, method = "pearson")

recall_tempclust_formodel_final <- merge(sf11_total_final_v2, temp_clust_11v2_new)


temp_clust_11v2_new <- temp_clust_11v2 %>% 
  mutate(condition = case_when(condition == "low"~"mid",
                               condition == "high"~"high",
                               condition == "control"~"control"))

recall_tempclust_formodel_final_cond <- recall_tempclust_formodel_final %>% 
  filter(between_condition == "novel")

recall_tempclust_formodel_final_cond<- recall_tempclust_formodel_final_cond %>% 
  mutate(condition = fct_relevel(condition, "mid", "control", "high"))

recall_tempclust_model_final<- glmer(recalls_final~temp_clust_score*condition +blocknum_contin +list_half+ (1|subject)+ (1|word_enc), family = binomial, data = recall_tempclust_formodel_final_cond)
summary(recall_tempclust_model_final)

```




```{r}
#source clustering analysis. Add a column for clustering by context, where each number is a context or image 

sf11_same_v2_source <- sf11_by_sub_v2_2 %>% 
  filter(blockcode == "mid_same" | blockcode == "mid_same2")



sf11_v2_total_encodingonly_new_source <- sf11_v2_total_encodingonly_new2 %>% 
  mutate(source = case_when(blockcode == "mid_same" & trialnum == "1" ~ "1",
                            blockcode == "mid_same" & trialnum == "2" ~ "1",
                            blockcode == "mid_same" & trialnum == "3" ~ "1",
                           blockcode == "mid_same" & trialnum == "4" ~ "1",
                           blockcode == "mid_same" & trialnum == "5" ~ "2",
                           blockcode == "mid_same" & trialnum == "6" ~ "2",
                            blockcode == "mid_same" & trialnum == "7" ~ "2",
                            blockcode == "mid_same" & trialnum == "8" ~ "2",
                            blockcode == "mid_same" & trialnum == "9" ~ "3",
                           blockcode == "mid_same" & trialnum == "10" ~ "3",
                             blockcode == "mid_same" & trialnum == "11" ~ "3",
                             blockcode == "mid_same" & trialnum == "12" ~ "3",
                             blockcode == "mid_same" & trialnum == "13" ~ "4",
                             blockcode == "mid_same" & trialnum == "14" ~ "4",
                             blockcode == "mid_same" & trialnum == "15" ~ "4",
                             blockcode == "mid_same" & trialnum == "16" ~ "4",
                             blockcode == "mid_same2" & trialnum == "1" ~ "5",
                             blockcode == "mid_same2" & trialnum == "2" ~ "5",
                             blockcode == "mid_same2" & trialnum == "3" ~ "5",
                             blockcode == "mid_same2" & trialnum == "4" ~ "5",
                             blockcode == "mid_same2" & trialnum == "5" ~ "6",
                            blockcode == "mid_same2" & trialnum == "6" ~ "6",
                             blockcode == "mid_same2" & trialnum == "7" ~ "6",
                             blockcode == "mid_same2" & trialnum == "8" ~ "6",
                             blockcode == "mid_same2" & trialnum == "9" ~ "7",
                             blockcode == "mid_same2" & trialnum == "10" ~ "7",
                             blockcode == "mid_same2" & trialnum == "11" ~ "7",
                             blockcode == "mid_same2" & trialnum == "12" ~ "7",
                             blockcode == "mid_same2" & trialnum == "13" ~ "8",
                             blockcode == "mid_same2" & trialnum == "14" ~ "8",
                             blockcode == "mid_same2" & trialnum == "15" ~ "8",
                             blockcode == "mid_same2" & trialnum == "16" ~ "8",
                             blockcode == "high_same2" & trialnum == "1" ~ "1",
                             blockcode == "high_same2" & trialnum == "2" ~ "1",
                            blockcode == "high_same2" & trialnum == "3" ~ "2",
                             blockcode == "high_same2" & trialnum == "4" ~ "2",
                             blockcode == "high_same2" & trialnum == "5" ~ "3",
                             blockcode == "high_same2" & trialnum == "6" ~ "3",
                             blockcode == "high_same2" & trialnum == "7" ~ "4",
                             blockcode == "high_same2" & trialnum == "8" ~ "4",
                             blockcode == "high_same2" & trialnum == "9" ~ "5",
                             blockcode == "high_same2" & trialnum == "10" ~ "5",
                             blockcode == "high_same2" & trialnum == "11" ~ "6",
                             blockcode == "high_same2" & trialnum == "12" ~ "6",
                             blockcode == "high_same2" & trialnum == "13" ~ "7",
                             blockcode == "high_same2" & trialnum == "14" ~ "7",
                             blockcode == "high_same2" & trialnum == "15" ~ "8",
                             blockcode == "high_same2" & trialnum == "16" ~ "8",
                             blockcode == "high_same" & trialnum == "1" ~ "9",
                             blockcode == "high_same" & trialnum == "2" ~ "9",
                             blockcode == "high_same" & trialnum == "3" ~ "10",
                             blockcode == "high_same" & trialnum == "4" ~ "10",
                             blockcode == "high_same" & trialnum == "5" ~ "11",
                             blockcode == "high_same" & trialnum == "6" ~ "11",
                             blockcode == "high_same" & trialnum == "7" ~ "12",
                             blockcode == "high_same" & trialnum == "8" ~ "12",
                             blockcode == "high_same" & trialnum == "9" ~ "13",
                             blockcode == "high_same" & trialnum == "10" ~ "13",
                             blockcode == "high_same" & trialnum == "11" ~ "14",
                             blockcode == "high_same" & trialnum == "12" ~ "14",
                             blockcode == "high_same" & trialnum == "13" ~ "15",
                             blockcode == "high_same" & trialnum == "14" ~ "15",
                             blockcode == "high_same" & trialnum == "15" ~ "16",
                             blockcode == "high_same" & trialnum == "16" ~ "16",
                             blockcode == "mid_novel" & trialnum == "1" ~ "1",
                             blockcode == "mid_novel" & trialnum == "2" ~ "1",
                             blockcode == "mid_novel" & trialnum == "3" ~ "1",
                             blockcode == "mid_novel" & trialnum == "4" ~ "1",
                             blockcode == "mid_novel" & trialnum == "5" ~ "2",
                             blockcode == "mid_novel" & trialnum == "6" ~ "2",
                             blockcode == "mid_novel" & trialnum == "7" ~ "2",
                             blockcode == "mid_novel" & trialnum == "8" ~ "2",
                             blockcode == "mid_novel" & trialnum == "9" ~ "3",
                             blockcode == "mid_novel" & trialnum == "10" ~ "3",
                             blockcode == "mid_novel" & trialnum == "11" ~ "3",
                             blockcode == "mid_novel" & trialnum == "12" ~ "3",
                             blockcode == "mid_novel" & trialnum == "13" ~ "4",
                             blockcode == "mid_novel" & trialnum == "14" ~ "4",
                             blockcode == "mid_novel" & trialnum == "15" ~ "4",
                             blockcode == "mid_novel" & trialnum == "16" ~ "4",
                             blockcode == "mid_novel2" & trialnum == "1" ~ "5",
                             blockcode == "mid_novel2" & trialnum == "2" ~ "5",
                             blockcode == "mid_novel2" & trialnum == "3" ~ "5",
                             blockcode == "mid_novel2" & trialnum == "4" ~ "5",
                             blockcode == "mid_novel2" & trialnum == "5" ~ "6",
                             blockcode == "mid_novel2" & trialnum == "6" ~ "6",
                             blockcode == "mid_novel2" & trialnum == "7" ~ "6",
                             blockcode == "mid_novel2" & trialnum == "8" ~ "6",
                             blockcode == "mid_novel2" & trialnum == "9" ~ "7",
                             blockcode == "mid_novel2" & trialnum == "10" ~ "7",
                             blockcode == "mid_novel2" & trialnum == "11" ~ "7",
                             blockcode == "mid_novel2" & trialnum == "12" ~ "7",
                             blockcode == "mid_novel2" & trialnum == "13" ~ "8",
                             blockcode == "mid_novel2" & trialnum == "14" ~ "8",
                             blockcode == "mid_novel2" & trialnum == "15" ~ "8",
                             blockcode == "mid_novel2" & trialnum == "16" ~ "8",
                             blockcode == "high_novel2" & trialnum == "1" ~ "1",
                             blockcode == "high_novel2" & trialnum == "2" ~ "1",
                             blockcode == "high_novel2" & trialnum == "3" ~ "2",
                            blockcode == "high_novel2" & trialnum == "4" ~ "2",
                             blockcode == "high_novel2" & trialnum == "5" ~ "3",
                             blockcode == "high_novel2" & trialnum == "6" ~ "3",
                             blockcode == "high_novel2" & trialnum == "7" ~ "4",
                             blockcode == "high_novel2" & trialnum == "8" ~ "4",
                             blockcode == "high_novel2" & trialnum == "9" ~ "5",
                             blockcode == "high_novel2" & trialnum == "10" ~ "5",
                             blockcode == "high_novel2" & trialnum == "11" ~ "6",
                             blockcode == "high_novel2" & trialnum == "12" ~ "6",
                             blockcode == "high_novel2" & trialnum == "13" ~ "7",
                             blockcode == "high_novel2" & trialnum == "14" ~ "7",
                             blockcode == "high_novel2" & trialnum == "15" ~ "8",
                             blockcode == "high_novel2" & trialnum == "16" ~ "8",
                             blockcode == "high_novel" & trialnum == "1" ~ "9",
                             blockcode == "high_novel" & trialnum == "2" ~ "9",
                             blockcode == "high_novel" & trialnum == "3" ~ "10",
                             blockcode == "high_novel" & trialnum == "4" ~ "10",
                             blockcode == "high_novel" & trialnum == "5" ~ "11",
                             blockcode == "high_novel" & trialnum == "6" ~ "11",
                             blockcode == "high_novel" & trialnum == "7" ~ "12",
                             blockcode == "high_novel" & trialnum == "8" ~ "12",
                             blockcode == "high_novel" & trialnum == "9" ~ "13",
                             blockcode == "high_novel" & trialnum == "10" ~ "13",
                             blockcode == "high_novel" & trialnum == "11" ~ "14",
                             blockcode == "high_novel" & trialnum == "12" ~ "14",
                             blockcode == "high_novel" & trialnum == "13" ~ "16",
                             blockcode == "high_novel" & trialnum == "14" ~ "16",
                             blockcode == "high_novel" & trialnum == "15" ~ "16",
                             blockcode == "high_novel" & trialnum == "16" ~ "16", 
                             blockcode == "control_same" & trialnum == "1" ~ "1",
                             blockcode == "control_same" & trialnum == "2" ~ "1",
                             blockcode == "control_same" & trialnum == "3" ~ "2",
                             blockcode == "control_same" & trialnum == "4" ~ "2",
                             blockcode == "control_same" & trialnum == "5" ~ "3",
                             blockcode == "control_same" & trialnum == "6" ~ "3",
                             blockcode == "control_same" & trialnum == "7" ~ "4",
                             blockcode == "control_same" & trialnum == "8" ~ "4",
                             blockcode == "control_same" & trialnum == "9" ~ "5",
                             blockcode == "control_same" & trialnum == "10" ~ "5",
                             blockcode == "control_same" & trialnum == "11" ~ "6",
                             blockcode == "control_same" & trialnum == "12" ~ "6",
                             blockcode == "control_same" & trialnum == "13" ~ "7",
                             blockcode == "control_same" & trialnum == "14" ~ "7",
                             blockcode == "control_same" & trialnum == "15" ~ "8",
                             blockcode == "control_same" & trialnum == "16" ~ "8",
                             blockcode == "control_same2" & trialnum == "1" ~ "9",
                             blockcode == "control_same2" & trialnum == "2" ~ "9",
                             blockcode == "control_same2" & trialnum == "3" ~ "10",
                             blockcode == "control_same2" & trialnum == "4" ~ "10",
                             blockcode == "control_same2" & trialnum == "5" ~ "11",
                            blockcode == "control_same2" & trialnum == "6" ~ "11",
                             blockcode == "control_same2" & trialnum == "7" ~ "12",
                             blockcode == "control_same2" & trialnum == "8" ~ "12",
                             blockcode == "control_same2" & trialnum == "9" ~ "13",
                             blockcode == "control_same2" & trialnum == "10" ~ "13",
                             blockcode == "control_same2" & trialnum == "11" ~ "14",
                             blockcode == "control_same2" & trialnum == "12" ~ "14",
                             blockcode == "control_same2" & trialnum == "13" ~ "15",
                             blockcode == "control_same2" & trialnum == "14" ~ "15",
                             blockcode == "control_same2" & trialnum == "15" ~ "16",
                             blockcode == "control_same2" & trialnum == "16" ~ "16",
                             blockcode == "control_novel" & trialnum == "1" ~ "1",
                             blockcode == "control_novel" & trialnum == "2" ~ "1",
                             blockcode == "control_novel" & trialnum == "3" ~ "2",
                             blockcode == "control_novel" & trialnum == "4" ~ "2",
                             blockcode == "control_novel" & trialnum == "5" ~ "3",
                             blockcode == "control_novel" & trialnum == "6" ~ "3",
                             blockcode == "control_novel" & trialnum == "7" ~ "4",
                             blockcode == "control_novel" & trialnum == "8" ~ "4",
                             blockcode == "control_novel" & trialnum == "9" ~ "5",
                             blockcode == "control_novel" & trialnum == "10" ~ "5",
                             blockcode == "control_novel" & trialnum == "11" ~ "6",
                             blockcode == "control_novel" & trialnum == "12" ~ "6",
                             blockcode == "control_novel" & trialnum == "13" ~ "7",
                             blockcode == "control_novel" & trialnum == "14" ~ "7",
                             blockcode == "control_novel" & trialnum == "15" ~ "8",
                             blockcode == "control_novel" & trialnum == "16" ~ "8",
                             blockcode == "control_novel2" & trialnum == "1" ~ "9",
                             blockcode == "control_novel2" & trialnum == "2" ~ "9",
                             blockcode == "control_novel2" & trialnum == "3" ~ "10",
                             blockcode == "control_novel2" & trialnum == "4" ~ "10",
                             blockcode == "control_novel2" & trialnum == "5" ~ "11",
                             blockcode == "control_novel2" & trialnum == "6" ~ "11",
                             blockcode == "control_novel2" & trialnum == "7" ~ "12",
                             blockcode == "control_novel2" & trialnum == "8" ~ "12",
                             blockcode == "control_novel2" & trialnum == "9" ~ "13",
                             blockcode == "control_novel2" & trialnum == "10" ~ "13",
                             blockcode == "control_novel2" & trialnum == "11" ~ "14",
                             blockcode == "control_novel2" & trialnum == "12" ~ "14",
                             blockcode == "control_novel2" & trialnum == "13" ~ "16",
                             blockcode == "control_novel2" & trialnum == "14" ~ "16",
                             blockcode == "control_novel2" & trialnum == "15" ~ "16",
                             blockcode == "control_novel2" & trialnum == "16" ~ "16"))

#lag it on the recall data frame, then if different from the trial before, make it a  0, if same make it a 1
#case when source == source new ?? 


split_enc_11_v2_source <- split(sf11_v2_total_encodingonly_new_source,sf11_v2_total_encodingonly_new_source$subject)
```



```{r}
#prepare the data for temporal clustering by adding necessary columns to the recall dataframe 

add_columns <- function(recall_df, enc_df) {
  selected_enc_df <- enc_df[, c("condition", "trialcode", "subject", "blocknum", "list_half", "task_switch" ,"trialnum", "blockcode", "word_enc", "source")]
  merged_df <- left_join(recall_df, selected_enc_df, by = c("V3" = "word_enc"))
  return(merged_df)
}

# Apply the function for each pair of recall and encoding data frames
merged_recall_list <- Map(add_columns, recall11_df_immed_2, split_enc_11_v2_source)

# Identify the common columns across all data frames
common_columns <- Reduce(intersect, lapply(merged_recall_list, colnames))

# Ensure that each data frame in the list contains only the common columns
cleaned_recall_list <- lapply(merged_recall_list, function(df) df[, common_columns])

# Combine the resulting data frames into one
recall11_df_immed_2_4 <- do.call("rbind", cleaned_recall_list)


```



```{r}
#remove all intrusions 
recall11_df_immed_2_5 <- recall11_df_immed_2_4 %>% 
  drop_na()

recall11_df_new <- merge(recall11_df_immed_2_5, recall11_df_immed_2_4)

#removes duplicates of a word 
recall11_df_new2 <- recall11_df_new %>% 
  group_by(subject) %>% 
  distinct(V2, .keep_all = TRUE)


```

```{r}
#source analysis set up

recall11_df_immed_2_3_source_full <- recall11_df_new2 %>% 
  mutate(source_new = lag(source))


recall11_df_immed_2_3_source_full$source <- as.integer(recall11_df_immed_2_3_source_full$source)
recall11_df_immed_2_3_source_full$source_new <- as.integer(recall11_df_immed_2_3_source_full$source_new)


```





```{r}

#source clustering mid - proportion 
recall11_df_immed_2_3_source <- recall11_df_new2 %>% 
  mutate(source_new = lag(source))





recall11_df_immed_2_3_source$source <- as.integer(recall11_df_immed_2_3_source$source)






recall11_df_immed_2_3_source$source_new <- as.integer(recall11_df_immed_2_3_source$source_new)

recall11_df_immed_2_3_source <- recall11_df_immed_2_3_source %>% 
  mutate(source_shift = case_when(source == source_new ~ 0, #context stays the same 
                                  source == source_new+1 ~ 1,
                                  source == source_new-1 ~ -1)) #context shifts 


recall11_df_immed_2_3_source_same_mid <- recall11_df_immed_2_3_source %>% 
  filter(blockcode == "mid_same"|blockcode == "mid_same2")


detach(package:Rmisc)
detach(package:plyr)



recall11_df_immed_2_3_source_same_tally_mid <- recall11_df_immed_2_3_source_same_mid %>% 
  group_by(subject) %>% 
  count(source_shift = factor(source_shift, c('-1', '0', '1')), .drop = FALSE) %>% 
  drop_na()


recall11_df_immed_2_3_source_same_tally_mid2 <- recall11_df_immed_2_3_source_same_tally_mid %>% 
  group_by(subject) %>% 
  mutate(denom = sum(n)) %>% 
  mutate(prop_source = n/denom) %>% 
  drop_na()





library(Rmisc)

source_same_prob_mid_full <- summarySEwithin(recall11_df_immed_2_3_source_same_tally_mid2, measurevar="prop_source", withinvars = c("source_shift"),idvar = "subject", na.rm=FALSE, conf.interval=.95)



source_same_prob_mid_full %>% 
  ggplot(aes(x = source_shift, y = prop_source)) +
  geom_col(width = .7, aes(fill = source_shift), alpha = .8, color = "black", size = .3) +
  labs(title    = "Number of shifts by source lag",
         x        = "Source Lag",
         y        = "proportion of local transitions")+
  theme_classic()+
  geom_errorbar(width=.1, position=position_dodge(.9), aes(ymin=prop_source-se, ymax=prop_source+se))+
  scale_y_continuous( expand = c(0,0))+
  scale_fill_manual(values = c("grey60", "green4", "darkorchid4"))




detach(package:Rmisc)
detach(package:plyr)

  

recall11_df_immed_2_3_source_novel_mid <- recall11_df_immed_2_3_source %>% 
  filter(blockcode == "mid_novel"|blockcode == "mid_novel2" )


recall11_df_immed_2_3_source_novel_mid$source_shift <- as.factor(recall11_df_immed_2_3_source_novel_mid$source_shift)



recall11_df_immed_2_3_source_novel_tally_mid <- recall11_df_immed_2_3_source_novel_mid %>% 
  group_by(subject) %>% 
  count(source_shift = factor(source_shift, c('-1', '0', '1')), .drop = FALSE) %>% 
  drop_na()


recall11_df_immed_2_3_source_novel_tally_mid2 <- recall11_df_immed_2_3_source_novel_tally_mid %>% 
  group_by(subject) %>% 
  mutate(denom = sum(n)) %>% 
  mutate(prop_source = n/denom) %>% 
  drop_na()


library(Rmisc)

source_novel_prob_mid_full <- summarySEwithin(recall11_df_immed_2_3_source_novel_tally_mid2, measurevar="prop_source", withinvars = c("source_shift"),idvar = "subject", na.rm=FALSE, conf.interval=.95)



source_novel_prob_mid_full %>% 
  ggplot(aes(x = source_shift, y = prop_source)) +
  geom_col(width = .7, aes(fill = source_shift), alpha = .8, color = "black", size = .3) +
  labs(title    = "Number of shifts by source lag",
         x        = "Source Lag",
         y        = "Number of shifts")+
  theme_classic()+
  geom_errorbar(width=.1, position=position_dodge(.9), aes(ymin=prop_source-se, ymax=prop_source+se))+
  scale_y_continuous( expand = c(0,0))+
  scale_fill_manual(values = c("grey60", "green4", "darkorchid4"))

```


```{r}
sf11_v2_total_encodingonly_new3 <- sf11_v2_total_encodingonly_new2 %>% 
  filter(!grepl('1', trialnum)) %>%
  filter(!grepl('2', trialnum)) %>% 
  filter(!(grepl('3', trialnum) & grepl('mid_same', blockcode))) %>% 
  filter(!(grepl('4', trialnum) & grepl('mid_same', blockcode))) %>% 
  filter(!(grepl('3', trialnum) & grepl('mid_same2', blockcode))) %>% 
  filter(!(grepl('4', trialnum) & grepl('mid_same2', blockcode))) %>% 
   filter(!(grepl('3', trialnum) & grepl('mid_novel', blockcode))) %>% 
  filter(!(grepl('4', trialnum) & grepl('mid_novel', blockcode))) %>% 
  filter(!(grepl('3', trialnum) & grepl('mid_novel2', blockcode))) %>% 
  filter(!(grepl('4', trialnum) & grepl('mid_novel2', blockcode)))
```




```{r}

#plots mid same and novel together 
source_same_prob_mid_full <- source_same_prob_mid_full %>% 
  mutate(between_condition = "same")

source_novel_prob_mid_full <- source_novel_prob_mid_full %>% 
  mutate(between_condition = "novel")

mid_combined_full <- rbind(source_same_prob_mid_full, source_novel_prob_mid_full)


mid_source_clust_full <- mid_combined_full %>% 
  ggplot(aes(x = source_shift, fill = interaction(between_condition,source_shift), y = prop_source)) +
  geom_bar(position="dodge", stat="identity", size = .3, alpha = .8) +
  labs(title    = "Source transitions",
         x        = "Transition Type",
         y        = "Proportion of Local Transitions")+
  theme_classic()+
  geom_errorbar(width=.1, position=position_dodge(.9), aes(ymin=prop_source-se, ymax=prop_source+se))+
  scale_y_continuous( expand = c(0,0))+
  scale_fill_manual(name = "Condition", values=c("grey60", "grey20", "green4", "darkorchid4", "green3", "lavender")) +
  facet_wrap(.~between_condition)

ggsave(plot=mid_source_clust_full, width = 8, height = 5, filename="~/mid_source_clust_full_se.pdf")

```

```{r}
#models for mid 
recall11_df_immed_2_3_source_novel_tally_mid2 <- recall11_df_immed_2_3_source_novel_tally_mid2 %>% 
  mutate(between_condition = "novel")

recall11_df_immed_2_3_source_same_tally_mid2 <- recall11_df_immed_2_3_source_same_tally_mid2 %>% 
  mutate(between_condition = "same")



recall11_immed_source_bind2_mid_2 <- rbind (recall11_df_immed_2_3_source_same_tally_mid2, recall11_df_immed_2_3_source_novel_tally_mid2)

library(lmerTest)
library(lme4)

recall11_immed_source_bind2_mid_cond <- recall11_immed_source_bind2_mid_2 %>% 
  filter(between_condition == "same")

recall11_immed_source_bind2_mid_cond<- recall11_immed_source_bind2_mid_cond %>% 
  mutate(source_shift = fct_relevel(source_shift, "0","1", "-1"))

model_mid_source_clust3 <- lmer(prop_source ~ source_shift + (1|subject),data = recall11_immed_source_bind2_mid_cond)
summary(model_mid_source_clust3)


model_mid_source_clust4 <- lmer(prop_source ~ source_shift*between_condition + (1|subject),data = recall11_immed_source_bind2_mid_2)
summary(model_mid_source_clust4)



```






```{r}

#source clustering high switch - proportion 

recall11_df_immed_2_3_source_same_high <- recall11_df_immed_2_3_source %>% 
  filter(blockcode == "high_same"|blockcode == "high_same2")


detach(package:Rmisc)
detach(package:plyr)


recall11_df_immed_2_3_source_same_high <- recall11_df_immed_2_3_source_same_high %>% 
  filter(!(grepl('1', source_new) & grepl('1', source_shift))) %>% 
  filter(!(grepl('1', source_new) & grepl('0', source_shift)))  %>%  
  drop_na() 


recall11_df_immed_2_3_source_same_tally_high <- recall11_df_immed_2_3_source_same_high %>% 
  group_by(subject) %>% 
  count(source_shift = factor(source_shift, c('-1', '0', '1')), .drop = FALSE) %>% 
  drop_na()


recall11_df_immed_2_3_source_same_tally_high2 <- recall11_df_immed_2_3_source_same_tally_high %>% 
  group_by(subject) %>% 
  mutate(denom = sum(n)) %>% 
  mutate(prop_source = n/denom)


recall11_df_immed_2_3_source_same_tally_high2$prop_source[is.nan(recall11_df_immed_2_3_source_same_tally_high2$prop_source)]<-0
  


library(Rmisc)

source_same_prob_high_full <- summarySEwithin(recall11_df_immed_2_3_source_same_tally_high2, measurevar="prop_source", withinvars = c("source_shift"),idvar = "subject", na.rm=FALSE, conf.interval=.95)



source_same_prob_high_full %>% 
  ggplot(aes(x = source_shift, y = prop_source)) +
  geom_col(width = .7, aes(fill = source_shift), alpha = .8, color = "black", size = .3) +
  labs(title    = "Number of shifts by source lag",
         x        = "Source Lag",
         y        = "Number of shifts")+
  theme_classic()+
  geom_errorbar(width=.1, position=position_dodge(.9), aes(ymin=prop_source-se, ymax=prop_source+se))+
  scale_y_continuous( expand = c(0,0))+
  scale_fill_manual(values = c("grey60", "green4", "darkorchid4"))




detach(package:Rmisc)
detach(package:plyr)


recall11_df_immed_2_3_source_novel_high <- recall11_df_immed_2_3_source %>% 
  filter(blockcode == "high_novel"|blockcode == "high_novel2")

recall11_df_immed_2_3_source_novel_high <- recall11_df_immed_2_3_source_novel_high %>% 
  filter(!(grepl('1', source_new) & grepl('1', source_shift))) %>% 
  filter(!(grepl('1', source_new) & grepl('0', source_shift)))  %>% 
  drop_na() 


recall11_df_immed_2_3_source_novel_tally_high <- recall11_df_immed_2_3_source_novel_high %>% 
  group_by(subject) %>% 
  count(source_shift = factor(source_shift, c('-1', '0', '1')), .drop = FALSE) %>% 
  drop_na()


recall11_df_immed_2_3_source_novel_tally_high2 <- recall11_df_immed_2_3_source_novel_tally_high %>% 
  group_by(subject) %>% 
  mutate(denom = sum(n)) %>% 
  mutate(prop_source = n/denom)


recall11_df_immed_2_3_source_novel_tally_high2$prop_source[is.nan(recall11_df_immed_2_3_source_novel_tally_high2$prop_source)]<-0


library(Rmisc)

source_novel_prob_high_full <- summarySEwithin(recall11_df_immed_2_3_source_novel_tally_high2, measurevar="prop_source", withinvars = c("source_shift"),idvar = "subject", na.rm=FALSE, conf.interval=.95)




source_novel_prob_high_full %>% 
  ggplot(aes(x = source_shift, y = prop_source)) +
  geom_col(width = .7, aes(fill = source_shift), alpha = .8, color = "black", size = .3) +
  labs(title    = "Number of shifts by source lag",
         x        = "Source Lag",
         y        = "Number of shifts")+
  theme_classic()+
  geom_errorbar(width=.1, position=position_dodge(.9), aes(ymin=prop_source-se, ymax=prop_source+se))+
  scale_y_continuous( expand = c(0,0))+
  scale_fill_manual(values = c("grey60", "green4", "darkorchid4"))
```



```{r}
source_same_prob_high_full <- source_same_prob_high_full %>% 
  mutate(between_condition = "same")

source_novel_prob_high_full <- source_novel_prob_high_full %>% 
  mutate(between_condition = "novel")

high_combined_full <- rbind(source_same_prob_high_full, source_novel_prob_high_full)


high_full<- high_combined_full %>% 
  ggplot(aes(x = source_shift, fill = interaction(between_condition,source_shift), y = prop_source)) +
  geom_bar(position="dodge", stat="identity", size = .3, alpha = .8) +
  labs(title    = "Source transitions",
         x        = "Transition Type",
         y        = "Proportion of Local Transitions")+
  theme_classic()+
  geom_errorbar(width=.1, position=position_dodge(.9), aes(ymin=prop_source-se, ymax=prop_source+se))+
  scale_y_continuous( expand = c(0,0))+
  scale_fill_manual(name = "Condition", values=c("grey60", "grey20", "grey60", "grey20", "grey60", "grey20")) +
  facet_wrap(.~between_condition)


ggsave(plot=high_full, width = 8, height = 5, filename="~/high_full_source_clustering.pdf")

```

```{r}
recall11_df_immed_2_3_source_novel_tally_high2 <- recall11_df_immed_2_3_source_novel_tally_high2 %>% 
  mutate(between_condition = "novel")

recall11_df_immed_2_3_source_same_tally_high2 <- recall11_df_immed_2_3_source_same_tally_high2 %>% 
  mutate(between_condition = "same")




recall11_immed_source_bind2 <- rbind (recall11_df_immed_2_3_source_same_tally_high2, recall11_df_immed_2_3_source_novel_tally_high2)

recall11_immed_source_bind2$source_shift <- as.factor(recall11_immed_source_bind2$source_shift)


recall11_immed_source_bind_cond <- recall11_immed_source_bind2 %>% 
  filter(between_condition == "novel")


recall11_immed_source_bind2<- recall11_immed_source_bind2 %>% 
  mutate(source_shift = fct_relevel(source_shift, "1", "0" , "-1"))

model_high_source_clust2<- lmer(prop_source~source_shift*between_condition+ (1|subject), data = recall11_immed_source_bind2)
summary(model_high_source_clust2)


model_high_source_clust3<- lmer(prop_source~source_shift+ (1|subject), data = recall11_immed_source_bind_cond)
summary(model_high_source_clust3)


plot_model(model_high_source_clust2, type = "pred")


```



```{r}
#source clustering high switch - available proportion 

recall11_df_immed_2_3_source_same_high <- recall11_df_immed_2_3_source %>% 
  filter(blockcode == "high_same"|blockcode == "high_same2")


detach(package:Rmisc)
detach(package:plyr)


recall11_df_immed_2_3_source_same_high_2 <- recall11_df_immed_2_3_source_same_high %>% 
  filter(!(grepl('1', source_new) & grepl('1', source_shift))) %>% 
  filter(!(grepl('1', source_new) & grepl('0', source_shift)))  %>%  
  drop_na() 


recall11_df_immed_2_3_source_same_tally_high <- recall11_df_immed_2_3_source_same_high %>% 
  group_by(subject) %>% 
  count(source_shift = factor(source_shift, c('-1', '0', '1')), .drop = FALSE) %>% 
  drop_na()


recall11_df_immed_2_3_source_same_tally_high_2 <- recall11_df_immed_2_3_source_same_tally_high %>% 
  group_by(subject) %>% 
  mutate(denom_fb = 28) %>% 
  mutate(denom_same = 16) %>% 
  mutate(prop_source =case_when(source_shift == -1 ~n/denom_fb,
                                source_shift == 1 ~n/denom_fb,
                                source_shift == 0 ~n/denom_same))


recall11_df_immed_2_3_source_same_tally_high_2$prop_source[is.nan(recall11_df_immed_2_3_source_same_tally_high_2$prop_source)]<-0
  


library(Rmisc)

source_same_prob_high_full_new <- summarySEwithin(recall11_df_immed_2_3_source_same_tally_high_2, measurevar="prop_source", withinvars = c("source_shift"),idvar = "subject", na.rm=FALSE, conf.interval=.95)



source_same_prob_high_full_new %>% 
  ggplot(aes(x = source_shift, y = prop_source)) +
  geom_col(width = .7, aes(fill = source_shift), alpha = .8, color = "black", size = .3) +
  labs(title    = "Number of shifts by source lag",
         x        = "Source Lag",
         y        = "Number of shifts")+
  theme_classic()+
  geom_errorbar(width=.1, position=position_dodge(.9), aes(ymin=prop_source-se, ymax=prop_source+se))+
  scale_y_continuous( expand = c(0,0))+
  scale_fill_manual(values = c("grey60", "green4", "darkorchid4"))




detach(package:Rmisc)
detach(package:plyr)


recall11_df_immed_2_3_source_novel_high <- recall11_df_immed_2_3_source %>% 
  filter(blockcode == "high_novel"|blockcode == "high_novel2")

recall11_df_immed_2_3_source_novel_high2 <- recall11_df_immed_2_3_source_novel_high %>% 
  filter(!(grepl('1', source_new) & grepl('1', source_shift))) %>% 
  filter(!(grepl('1', source_new) & grepl('0', source_shift)))  %>% 
  drop_na() 


recall11_df_immed_2_3_source_novel_tally_high <- recall11_df_immed_2_3_source_novel_high %>% 
  group_by(subject) %>% 
  count(source_shift = factor(source_shift, c('-1', '0', '1')), .drop = FALSE) %>% 
  drop_na()


recall11_df_immed_2_3_source_novel_tally_high_2 <- recall11_df_immed_2_3_source_novel_tally_high %>% 
  group_by(subject) %>% 
  mutate(denom_fb = 28) %>% 
  mutate(denom_same = 16) %>% 
  mutate(prop_source =case_when(source_shift == -1 ~n/denom_fb,
                                source_shift == 1 ~n/denom_fb,
                                source_shift == 0 ~n/denom_same))


recall11_df_immed_2_3_source_novel_tally_high_2$prop_source[is.nan(recall11_df_immed_2_3_source_novel_tally_high_2$prop_source)]<-0


library(Rmisc)

source_novel_prob_high_full_2 <- summarySEwithin(recall11_df_immed_2_3_source_novel_tally_high_2, measurevar="prop_source", withinvars = c("source_shift"),idvar = "subject", na.rm=FALSE, conf.interval=.95)




source_novel_prob_high_full_2 %>% 
  ggplot(aes(x = source_shift, y = prop_source)) +
  geom_col(width = .7, aes(fill = source_shift), alpha = .8, color = "black", size = .3) +
  labs(title    = "Number of shifts by source lag",
         x        = "Source Lag",
         y        = "Number of shifts")+
  theme_classic()+
  geom_errorbar(width=.1, position=position_dodge(.9), aes(ymin=prop_source-se, ymax=prop_source+se))+
  scale_y_continuous( expand = c(0,0))+
  scale_fill_manual(values = c("grey60", "green4", "darkorchid4"))
```


```{r}
source_same_prob_high_full_2 <- source_same_prob_high_full_new %>% 
  mutate(between_condition = "same")

source_novel_prob_high_full_new <- source_novel_prob_high_full_2 %>% 
  mutate(between_condition = "novel")

high_combined_full_2 <- rbind(source_same_prob_high_full_2, source_novel_prob_high_full_new)


high_full_2<- high_combined_full_2 %>% 
  ggplot(aes(x = source_shift, fill = interaction(between_condition,source_shift), y = prop_source)) +
  geom_bar(position="dodge", stat="identity", size = .3, alpha = .8) +
  labs(title    = "Source transitions",
         x        = "Transition Type",
         y        = "Local Transition Probability")+
  theme_classic()+
  geom_errorbar(width=.1, position=position_dodge(.9), aes(ymin=prop_source-se, ymax=prop_source+se))+
  scale_y_continuous( expand = c(0,0))+
  scale_fill_manual(name = "Condition", values=c("grey60", "grey20", "grey60", "grey20", "grey60", "grey20")) +
  facet_wrap(.~between_condition)


ggsave(plot=high_full_2, width = 8, height = 5, filename="~/high_full_source_clustering_new.pdf")
```

```{r}
recall11_df_immed_2_3_source_novel_tally_high_2 <- recall11_df_immed_2_3_source_novel_tally_high_2 %>% 
  mutate(between_condition = "novel")

recall11_df_immed_2_3_source_same_tally_high_2 <- recall11_df_immed_2_3_source_same_tally_high_2 %>% 
  mutate(between_condition = "same")




source_transition_new_both<- rbind (recall11_df_immed_2_3_source_same_tally_high_2, recall11_df_immed_2_3_source_novel_tally_high_2)

source_transition_new_both$source_shift <- as.factor(source_transition_new_both$source_shift)


recall11_immed_source_bind_cond2 <- source_transition_new_both %>% 
  filter(between_condition == "same")


source_transition_new_both<- source_transition_new_both %>% 
  mutate(source_shift = fct_relevel(source_shift, "0", "1" , "-1"))

model_high_source_clust_2<- lmer(prop_source~source_shift*between_condition+ (1|subject), data = source_transition_new_both)
summary(model_high_source_clust_2)

plot_model(model_high_source_clust_2, type = "int")

r2glmm::r2beta(model_high_source_clust_2, partial = TRUE)


model_high_source_clust_3<- lmer(prop_source~source_shift+ (1|subject), data = recall11_immed_source_bind_cond2)
summary(model_high_source_clust_3)

plot_model(model_high_source_clust_3, type = "pred")

r2glmm::r2beta(model_high_source_clust_3, partial = TRUE)




source_transition_new_both_1_same<- source_transition_new_both %>% 
  filter(source_shift == "1") %>% 
  filter(between_condition == "same")


source_transition_new_both_1_novel<- source_transition_new_both %>% 
  filter(source_shift == "1") %>% 
  filter(between_condition == "novel")
  

t.test(source_transition_new_both_1_same$prop_source, source_transition_new_both_1_novel$prop_source)

```

```{r}
#source clustering high switch - available proportion 

recall11_df_immed_2_3_source_same_mid <- recall11_df_immed_2_3_source %>% 
  filter(blockcode == "mid_same"|blockcode == "mid_same2")


detach(package:Rmisc)
detach(package:plyr)


recall11_df_immed_2_3_source_same_mid_2 <- recall11_df_immed_2_3_source_same_mid %>% 
  filter(!(grepl('1', source_new) & grepl('1', source_shift))) %>% 
  filter(!(grepl('1', source_new) & grepl('0', source_shift)))  %>%  
  drop_na() 


recall11_df_immed_2_3_source_same_tally_mid <- recall11_df_immed_2_3_source_same_mid %>% 
  group_by(subject) %>% 
  count(source_shift = factor(source_shift, c('-1', '0', '1')), .drop = FALSE) %>% 
  drop_na()


recall11_df_immed_2_3_source_same_tally_mid_2 <- recall11_df_immed_2_3_source_same_tally_mid %>% 
  group_by(subject) %>% 
  mutate(denom_fb = 48) %>% 
  mutate(denom_same = 48) %>% 
  mutate(prop_source =case_when(source_shift == -1 ~n/denom_fb,
                                source_shift == 1 ~n/denom_fb,
                                source_shift == 0 ~n/denom_same))


recall11_df_immed_2_3_source_same_tally_mid_2$prop_source[is.nan(recall11_df_immed_2_3_source_same_tally_mid_2$prop_source)]<-0
  


library(Rmisc)

source_same_prob_mid_full_new <- summarySEwithin(recall11_df_immed_2_3_source_same_tally_mid_2, measurevar="prop_source", withinvars = c("source_shift"),idvar = "subject", na.rm=FALSE, conf.interval=.95)



source_same_prob_mid_full_new %>% 
  ggplot(aes(x = source_shift, y = prop_source)) +
  geom_col(width = .7, aes(fill = source_shift), alpha = .8, color = "black", size = .3) +
  labs(title    = "Number of shifts by source lag",
         x        = "Source Lag",
         y        = "Number of shifts")+
  theme_classic()+
  geom_errorbar(width=.1, position=position_dodge(.9), aes(ymin=prop_source-se, ymax=prop_source+se))+
  scale_y_continuous( expand = c(0,0))+
  scale_fill_manual(values = c("grey60", "green4", "darkorchid4"))




detach(package:Rmisc)
detach(package:plyr)


recall11_df_immed_2_3_source_novel_mid <- recall11_df_immed_2_3_source %>% 
  filter(blockcode == "mid_novel"|blockcode == "mid_novel2")

recall11_df_immed_2_3_source_novel_mid2 <- recall11_df_immed_2_3_source_novel_mid %>% 
  filter(!(grepl('1', source_new) & grepl('1', source_shift))) %>% 
  filter(!(grepl('1', source_new) & grepl('0', source_shift)))  %>% 
  drop_na() 


recall11_df_immed_2_3_source_novel_tally_mid <- recall11_df_immed_2_3_source_novel_mid %>% 
  group_by(subject) %>% 
  count(source_shift = factor(source_shift, c('-1', '0', '1')), .drop = FALSE) %>% 
  drop_na()


recall11_df_immed_2_3_source_novel_tally_mid_2 <- recall11_df_immed_2_3_source_novel_tally_mid %>% 
  group_by(subject) %>% 
  mutate(denom_fb = 48) %>% 
  mutate(denom_same = 48) %>% 
  mutate(prop_source =case_when(source_shift == -1 ~n/denom_fb,
                                source_shift == 1 ~n/denom_fb,
                                source_shift == 0 ~n/denom_same))


recall11_df_immed_2_3_source_novel_tally_mid_2$prop_source[is.nan(recall11_df_immed_2_3_source_novel_tally_mid_2$prop_source)]<-0


library(Rmisc)

source_novel_prob_mid_full_2 <- summarySEwithin(recall11_df_immed_2_3_source_novel_tally_mid_2, measurevar="prop_source", withinvars = c("source_shift"),idvar = "subject", na.rm=FALSE, conf.interval=.95)




source_novel_prob_mid_full_2 %>% 
  ggplot(aes(x = source_shift, y = prop_source)) +
  geom_col(width = .7, aes(fill = source_shift), alpha = .8, color = "black", size = .3) +
  labs(title    = "Number of shifts by source lag",
         x        = "Source Lag",
         y        = "Number of shifts")+
  theme_classic()+
  geom_errorbar(width=.1, position=position_dodge(.9), aes(ymin=prop_source-se, ymax=prop_source+se))+
  scale_y_continuous( expand = c(0,0))+
  scale_fill_manual(values = c("grey60", "green4", "darkorchid4"))
```


```{r}
source_same_prob_mid_full_2 <- source_same_prob_mid_full_new %>% 
  mutate(between_condition = "same")

source_novel_prob_mid_full_new <- source_novel_prob_mid_full_2 %>% 
  mutate(between_condition = "novel")

mid_combined_full_2 <- rbind(source_same_prob_mid_full_2, source_novel_prob_mid_full_new)


mid_full_2<- mid_combined_full_2 %>% 
  ggplot(aes(x = source_shift, fill = interaction(between_condition,source_shift), y = prop_source)) +
  geom_bar(position="dodge", stat="identity", size = .3, alpha = .8) +
  labs(title    = "Source transitions",
         x        = "Transition Type",
         y        = "Local Transition Probability")+
  theme_classic()+
  geom_errorbar(width=.1, position=position_dodge(.9), aes(ymin=prop_source-se, ymax=prop_source+se))+
  scale_y_continuous( expand = c(0,0), limits = c(0,.17))+
  scale_fill_manual(name = "Condition", values=c("grey60", "grey20", "grey60", "grey20", "grey60", "grey20")) +
  facet_wrap(.~between_condition)


ggsave(plot=mid_full_2, width = 8, height = 5, filename="~/mid_full_source_clustering_new.pdf")
```


```{r}
recall11_df_immed_2_3_source_novel_tally_mid_2 <- recall11_df_immed_2_3_source_novel_tally_mid_2 %>% 
  mutate(between_condition = "novel")

recall11_df_immed_2_3_source_same_tally_mid_2 <- recall11_df_immed_2_3_source_same_tally_mid_2 %>% 
  mutate(between_condition = "same")




source_transition_new_both_mid<- rbind (recall11_df_immed_2_3_source_same_tally_mid_2, recall11_df_immed_2_3_source_novel_tally_mid_2)

source_transition_new_both_mid$source_shift <- as.factor(source_transition_new_both_mid$source_shift)


recall11_immed_source_bind_cond2 <- source_transition_new_both_mid %>% 
  filter(between_condition == "same")


source_transition_new_both_mid<- source_transition_new_both_mid %>% 
  mutate(source_shift = fct_relevel(source_shift, "0", "1" , "-1"))

model_mid_source_clust_2<- lmer(prop_source~source_shift*between_condition+ (1|subject), data = source_transition_new_both_mid)
summary(model_mid_source_clust_2)

plot_model(model_mid_source_clust_2, type = "int")


model_mid_source_clust_3<- lmer(prop_source~source_shift+ (1|subject), data = recall11_immed_source_bind_cond2)
summary(model_mid_source_clust_3)

plot_model(model_mid_source_clust_3, type = "pred")
```


#FINAL RECALL

```{r}
#removes primacy items - removing first two switches for final recall 


sf11_total_v2_high_2 <- sf11_v2_total_encodingonly_new2 %>% 
  filter(condition == "high") %>% 
   filter(trialnum == "5"| trialnum == "6"|trialnum == "7"| trialnum == "8"| trialnum == "9"| trialnum == "10"| trialnum == "11"| trialnum == "12"| trialnum == "13"| trialnum == "14"| trialnum == "15"| trialnum == "16")
  
  

sf11_total_v2_low_2 <- sf11_v2_total_encodingonly_new2 %>% 
  filter(condition == "mid") %>% 
   filter(trialnum == "9"| trialnum == "10"| trialnum == "11"| trialnum == "12"| trialnum == "13"| trialnum == "14"| trialnum == "15"| trialnum == "16")

sf11_total_v2_control3<- sf11_v2_total_encodingonly_new2 %>% 
  filter(condition == "control")



sf11_v2_total_encodingonly_new2 <- rbind(sf11_total_v2_high_2,sf11_total_v2_low_2, sf11_total_v2_control3) %>% 
  arrange(by = subject, blocknum)



```



```{r}
#most important code chunk- final recall 
library(stringr)
detach(package:Rmisc) 
detach(package:plyr) #MUST RUN THIS

split_enc_11_v2 <- split(sf11_v2_total_encodingonly_new2,sf11_v2_total_encodingonly_new2$subject)

#list of all subjects individual recall data
recall11_df_final_2 = list(
  final_recall_3878, final_recall_3879, final_recall_3880, final_recall_3882,
  final_recall_3885, final_recall_3886, final_recall_3893, final_recall_3895,
  final_recall_3896, final_recall_3902, final_recall_3905, final_recall_3907,
  final_recall_3908, final_recall_3913, final_recall_3916, final_recall_3918,
  final_recall_3919, final_recall_3927, final_recall_3928, final_recall_3929,
  final_recall_3935, final_recall_3938, final_recall_3939, final_recall_3940,
  final_recall_3943, final_recall_3944, final_recall_3945, final_recall_3946,
  final_recall_3948, final_recall_3949, final_recall_3953, final_recall_3954,
  final_recall_3955, final_recall_3957, final_recall_3958, final_recall_3959,
  final_recall_3960, final_recall_3964, final_recall_3967, final_recall_3969,
  final_recall_3971, final_recall_3973, final_recall_3976, final_recall_3977,
  final_recall_3980, final_recall_3981, final_recall_3983, final_recall_3984,
  final_recall_3989, final_recall_3990, final_recall_3991, final_recall_3992,
  final_recall_3993, final_recall_4002, final_recall_4006, final_recall_4007,
  final_recall_4008, final_recall_4010, final_recall_4011, final_recall_4012,
  final_recall_4013, final_recall_4014, final_recall_4017, final_recall_4019,
  final_recall_4021, final_recall_4024, final_recall_4025, final_recall_4026,
  final_recall_4027, final_recall_4028, final_recall_4030, final_recall_4034,
  final_recall_4038, final_recall_4039, final_recall_4046, final_recall_4048,
  final_recall_4049, final_recall_4051, final_recall_4052, final_recall_4053,
  final_recall_4055, final_recall_4056, final_recall_4057, final_recall_4059,
  final_recall_4063, final_recall_4068, final_recall_4071, final_recall_4074,
  final_recall_4076, final_recall_4078, final_recall_4079, final_recall_4080,
  final_recall_4081, final_recall_4089, final_recall_4090, final_recall_4092,
  final_recall_4093, final_recall_4094, final_recall_4096, final_recall_4097,
  final_recall_4098, final_recall_4101, final_recall_4102, final_recall_4103,
  final_recall_4104, final_recall_4106, final_recall_4108, final_recall_4109,
  final_recall_4115, final_recall_4116, final_recall_4119, final_recall_4122,
  final_recall_4124, final_recall_4126, final_recall_4127, final_recall_4129,
  final_recall_4130, final_recall_4132, final_recall_4135, final_recall_4137,
  final_recall_4138, final_recall_4140, final_recall_4141, final_recall_4147,
  final_recall_4148, final_recall_4149, final_recall_4151, final_recall_4153)




#list of task data 
sf11_by_sub_v2 <- list(split_enc_11_v2$`3878`, split_enc_11_v2$'3879', split_enc_11_v2$'3880', split_enc_11_v2$'3882', split_enc_11_v2$'3885', split_enc_11_v2$'3886', split_enc_11_v2$'3893', split_enc_11_v2$'3895', split_enc_11_v2$'3896', split_enc_11_v2$'3902', split_enc_11_v2$'3905', split_enc_11_v2$'3907', split_enc_11_v2$'3908', split_enc_11_v2$'3913', split_enc_11_v2$'3916', split_enc_11_v2$'3918', split_enc_11_v2$'3919', split_enc_11_v2$'3927', split_enc_11_v2$'3928', split_enc_11_v2$'3929', split_enc_11_v2$'3935', split_enc_11_v2$'3938', split_enc_11_v2$'3939', split_enc_11_v2$'3940', split_enc_11_v2$'3943', split_enc_11_v2$'3944', split_enc_11_v2$'3945', split_enc_11_v2$'3946', split_enc_11_v2$'3948', split_enc_11_v2$'3949', split_enc_11_v2$'3953', split_enc_11_v2$'3954', split_enc_11_v2$'3955', split_enc_11_v2$'3957', split_enc_11_v2$'3958', split_enc_11_v2$'3959', split_enc_11_v2$'3960', split_enc_11_v2$'3964', split_enc_11_v2$'3967', split_enc_11_v2$'3969', split_enc_11_v2$'3971', split_enc_11_v2$'3973', split_enc_11_v2$'3976', split_enc_11_v2$'3977', split_enc_11_v2$'3980', split_enc_11_v2$'3981', split_enc_11_v2$'3983', split_enc_11_v2$'3984', split_enc_11_v2$'3989', split_enc_11_v2$'3990', split_enc_11_v2$'3991', split_enc_11_v2$'3992', split_enc_11_v2$'3993', split_enc_11_v2$'4002', split_enc_11_v2$'4006', split_enc_11_v2$'4007', split_enc_11_v2$'4008', split_enc_11_v2$'4010',split_enc_11_v2$'4011', split_enc_11_v2$'4012',split_enc_11_v2$'4013', split_enc_11_v2$'4014', split_enc_11_v2$'4017', split_enc_11_v2$'4019', split_enc_11_v2$'4021', split_enc_11_v2$'4024', split_enc_11_v2$'4025', split_enc_11_v2$'4026', split_enc_11_v2$'4027', split_enc_11_v2$'4028', split_enc_11_v2$'4030', split_enc_11_v2$'4034', split_enc_11_v2$'4038', split_enc_11_v2$'4039', split_enc_11_v2$'4046', split_enc_11_v2$'4048', split_enc_11_v2$'4049', split_enc_11_v2$'4051', split_enc_11_v2$'4052', split_enc_11_v2$'4053', split_enc_11_v2$'4055', split_enc_11_v2$'4056', split_enc_11_v2$'4057', split_enc_11_v2$'4059', split_enc_11_v2$'4063', split_enc_11_v2$'4068', split_enc_11_v2$'4071', split_enc_11_v2$'4074', split_enc_11_v2$'4076', split_enc_11_v2$'4078', split_enc_11_v2$'4079', split_enc_11_v2$'4080', split_enc_11_v2$'4081', split_enc_11_v2$'4089', split_enc_11_v2$'4090', split_enc_11_v2$'4092', split_enc_11_v2$'4093', split_enc_11_v2$'4094',split_enc_11_v2$'4096', split_enc_11_v2$'4097', split_enc_11_v2$'4098', split_enc_11_v2$`4101`, split_enc_11_v2$`4102`,  split_enc_11_v2$`4103`, split_enc_11_v2$`4104`, split_enc_11_v2$`4106`, split_enc_11_v2$`4108`, split_enc_11_v2$`4109`, split_enc_11_v2$`4115`, split_enc_11_v2$`4116`, split_enc_11_v2$`4119`, split_enc_11_v2$`4122`, split_enc_11_v2$`4124`, split_enc_11_v2$`4126`, split_enc_11_v2$`4127`, split_enc_11_v2$`4129`, split_enc_11_v2$`4130`, split_enc_11_v2$`4132`, split_enc_11_v2$`4135`, split_enc_11_v2$'4137', split_enc_11_v2$'4138', split_enc_11_v2$'4140', split_enc_11_v2$'4141', split_enc_11_v2$'4147', split_enc_11_v2$'4148', split_enc_11_v2$'4149', split_enc_11_v2$'4151', split_enc_11_v2$'4154', split_enc_11_v2$'4156', split_enc_11_v2$'4159', split_enc_11_v2$'4160', split_enc_11_v2$'4165', split_enc_11_v2$'4166', split_enc_11_v2$'4169', split_enc_11_v2$'4171', split_enc_11_v2$'4173', split_enc_11_v2$'4175', split_enc_11_v2$'4176', split_enc_11_v2$'4177', split_enc_11_v2$'4179', split_enc_11_v2$'4180', split_enc_11_v2$'4182', split_enc_11_v2$'4183', split_enc_11_v2$'4185', split_enc_11_v2$'4186', split_enc_11_v2$'4187', split_enc_11_v2$'4192', split_enc_11_v2$'4193', split_enc_11_v2$'4194', split_enc_11_v2$'4196', split_enc_11_v2$'4202', split_enc_11_v2$'4206', split_enc_11_v2$'4211', split_enc_11_v2$'4213', split_enc_11_v2$'4216', split_enc_11_v2$'4217', split_enc_11_v2$'4219', split_enc_11_v2$'4220', split_enc_11_v2$'4222', split_enc_11_v2$'4224', split_enc_11_v2$'4225', split_enc_11_v2$'4229', split_enc_11_v2$'4230', split_enc_11_v2$'4238', split_enc_11_v2$'4239', split_enc_11_v2$'4242', split_enc_11_v2$'4153')


#for every subject:
c = 0 
for (ssid in array(1:length(recall11_df_final_2))){
    i = sf11_by_sub_v2[[ssid]]
    j = recall11_df_final_2[[ssid]]
    c = c +1 
    output  <- i %>% 
      mutate(recalls_final = tolower(word_enc) %in% tolower(j$V3))%>%  #matches the recall with task word
      mutate(recalls_final = case_when(recalls_final == "TRUE" ~ 1, #if recalled word, puts a 1 
                               recalls_final == "FALSE" ~ 0)) %>%  
      group_by(condition, trialcode) %>% 
      mutate(sum_recall = sum(recalls_final)) %>% # this column sums the recalls by condition and task
      group_by(blocknum) %>% 
      mutate(sum_recall_block = sum(recalls_final)) %>% #sums recalls by block
      group_by(trialcode) %>% 
      mutate(sum_recall_trialcode = sum(recalls_final)) #sums recalls just by task 
    if (c ==1) {
      sf11_total_final_v2 = output
    } else {
      sf11_total_final_v2 = rbind(sf11_total_final_v2,output)
    }}

sf11_total_final_v2 
```

```{r}
#recall by task 
library(dplyr)
detach(package:Rmisc) 
detach(package:plyr)


sf11_total_final_v2_2<- sf11_total_final_v2 %>% 
  group_by(subject) %>% 
  mutate(recall_percent2 = sum(recalls_final)/96*100) %>% 
  summarise(mean_rec = mean(recall_percent2, na.rm = TRUE))
sf11_total_final_v2_2



#plot of each subjects recall in order 
sf11_total_final_v2_2 %>% 
  ggplot(aes(x = reorder(as.character(subject), mean_rec), y = mean_rec))+
  geom_col(fill = "orchid", width = .8)+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 45,hjust = 1))+
  labs(title    = "Percent of Total Words Recalled",
         x        = "Subject Number",
         y        = "Percent Recalled")


mean_recall11_fin2 <- mean(sf11_total_final_v2_2$mean_rec, na.rm = TRUE)
mean_recall11_fin2


sd_11_fin_2 <-sd(sf11_total_final_v2_2$mean_rec, na.rm = TRUE)
```


```{r}
#compare means between same and novel 

sf11_total_final_v2_between<- sf11_total_final_v2 %>% 
  group_by(subject, between_condition) %>% 
  mutate(recall_percent2 = sum(recalls_final)/96*100) %>% 
  summarise(mean_rec = mean(recall_percent2, na.rm = TRUE))
sf11_total_final_v2_between

sf11_total_final_v2_between_same <- sf11_total_final_v2_between %>% 
  filter(between_condition == "same")


mean_recall11_same2<- mean(sf11_total_final_v2_between_same$mean_rec, na.rm = TRUE)
mean_recall11_same2


sf11_total_final_v2_between_novel <- sf11_total_final_v2_between %>% 
  filter(between_condition == "novel")

mean_recall11_novel2<- mean(sf11_total_final_v2_between_novel$mean_rec, na.rm = TRUE)
mean_recall11_novel2


t.test(sf11_total_final_v2_between_same$mean_rec, sf11_total_final_v2_between_novel$mean_rec)
```



```{r}
#outliers at final recall
sf11_total_final_v2_2 %>% 
  arrange(mean_rec)


sd_11_fin_2 <-sd(sf11_total_final_v2_2$mean_rec, na.rm = TRUE)

mean_recall11_fin2 <- mean(sf11_total_final_v2_2$mean_rec, na.rm = TRUE)

mean_recall11_fin2 + (3 * sd_11_fin_2) 
mean_recall11_fin2 - (3 * sd_11_fin_2) 

```


```{r}
#separate between conditions 

sf11_total_same_fin_v2 <- sf11_total_final_v2 %>% 
  filter(between_condition == "same")


sf11_total_novel_fin_v2 <- sf11_total_final_v2 %>% 
  filter(between_condition == "novel")
```





```{r}
#remove primacy items
sf11_total_v2_high_same2 <- sf11_total_same_fin_v2 %>% 
  filter(condition == "high") %>% 
   filter(trialnum == "5"| trialnum == "6"|trialnum == "7"| trialnum == "8"| trialnum == "9"| trialnum == "10"| trialnum == "11"| trialnum == "12"| trialnum == "13"| trialnum == "14"| trialnum == "15"| trialnum == "16")
  
  

sf11_total_v2_low_same2 <- sf11_total_same_fin_v2 %>% 
  filter(condition == "mid") %>% 
   filter(trialnum == "9"| trialnum == "10"| trialnum == "11"| trialnum == "12"| trialnum == "13"| trialnum == "14"| trialnum == "15"| trialnum == "16")

sf11_total_v2_control2 <- sf11_total_same_fin_v2 %>% 
  filter(condition == "control")



sf11_total_same_fin_v2 <- rbind(sf11_total_v2_high_same2,sf11_total_v2_low_same2, sf11_total_v2_control2) %>% 
  arrange(by = subject, blocknum)



sf11_total_v2_high_novel2 <- sf11_total_novel_fin_v2 %>% 
  filter(condition == "high") %>% 
   filter(trialnum == "5"| trialnum == "6"|trialnum == "7"| trialnum == "8"| trialnum == "9"| trialnum == "10"| trialnum == "11"| trialnum == "12"| trialnum == "13"| trialnum == "14"| trialnum == "15"| trialnum == "16")


 sf11_total_v2_low_novel2 <- sf11_total_novel_fin_v2 %>% 
  filter(condition == "mid") %>% 
   filter(trialnum == "9"| trialnum == "10"| trialnum == "11"| trialnum == "12"| trialnum == "13"| trialnum == "14"| trialnum == "15"| trialnum == "16") 
 
 

sf11_total_v2_control_novel2 <- sf11_total_novel_fin_v2 %>% 
  filter(condition == "control")



sf11_total_novel_fin_v2 <- rbind(sf11_total_v2_high_novel2,sf11_total_v2_low_novel2, sf11_total_v2_control_novel2) %>% 
  arrange(by = subject, blocknum)
```







```{r}
#plot average recalls for task and condition- final 

#separate control into high and mid paired 
#no switch items in the control 

#JUST same

#main plot chunk 
detach(package:Rmisc)
detach(package:plyr)


sf12_total_tally_same_final2 <- sf11_total_same_fin_v2 %>% 
  group_by(subject, condition) %>% 
  tally() 
sf12_total_tally_same_final2


sf12_total_same_v2_fin <- sf11_total_same_fin_v2 %>% 
  dplyr:: select(subject, condition, trialcode, sum_recall, recalls_final) %>% 
  group_by(subject, condition) %>% 
  mutate(sum_recall2 = sum(recalls_final)) %>% 
  summarise(mean_rec_cond = mean(sum_recall2)) 

merged_same2_fin <- merge(sf12_total_same_v2_fin,sf12_total_tally_same_final2)


merged_same2_fin <- merged_same2_fin %>% 
  mutate(prop_cond = mean_rec_cond/n)

merged_same2_fin<- merged_same2_fin %>% 
  mutate(condition = fct_relevel(condition, "control", "mid", "high"))

library(Rmisc)

condition_same_fin2 <- summarySEwithin(merged_same2_fin, measurevar="prop_cond", withinvars = c("condition"),idvar = "subject", na.rm=FALSE, conf.interval=.95)



condition_same_fin2 %>% 
  ggplot(aes(x = condition, y = prop_cond)) +
  geom_col(width = .7, aes(fill = condition), alpha = .8, color = "black", size = .3) +
  labs(title    = "Percentage of Recalls by Condition",
         x        = "Condition",
         y        = "Percent Recalled")+
  theme_classic()+
  geom_errorbar(width=.1, position=position_dodge(.9), aes(ymin=prop_cond-ci, ymax=prop_cond+ci))+
  scale_y_continuous(labels = scales::percent, expand = c(0,0))+
  scale_x_discrete(labels=c("control" = "Control","mid"= "Low Switch", "high" = "High Switch"))+
    scale_fill_manual(values = c("grey60", "darkorchid4", "darkgreen"))
```

```{r}
#plot average recalls for task and condition- final 

#separate control into high and mid paired 
#no switch items in the control 

#JUST novel

#main plot chunk 
detach(package:Rmisc)
detach(package:plyr)


sf12_total_tally_novel_final2 <- sf11_total_novel_fin_v2 %>% 
  group_by(subject, condition) %>% 
  tally() 
sf12_total_tally_novel_final2


sf12_total_novel_v2_fin <- sf11_total_novel_fin_v2 %>% 
  dplyr:: select(subject, condition, trialcode, sum_recall, recalls_final) %>% 
  group_by(subject, condition) %>% 
  mutate(sum_recall2 = sum(recalls_final)) %>% 
  summarise(mean_rec_cond = mean(sum_recall2)) 

merged_novel2_fin <- merge(sf12_total_novel_v2_fin,sf12_total_tally_novel_final2)


merged_novel2_fin <- merged_novel2_fin %>% 
  mutate(prop_cond = mean_rec_cond/n)

merged_novel2_fin<- merged_novel2_fin %>% 
  mutate(condition = fct_relevel(condition, "control", "mid", "high"))

library(Rmisc)

condition_novel_fin2 <- summarySEwithin(merged_novel2_fin, measurevar="prop_cond", withinvars = c("condition"),idvar = "subject", na.rm=FALSE, conf.interval=.95)



condition_novel_fin2 %>% 
  ggplot(aes(x = condition, y = prop_cond)) +
  geom_col(width = .7, aes(fill = condition), alpha = .8, color = "black", size = .3) +
  labs(title    = "Percentage of Recalls by Condition",
         x        = "Condition",
         y        = "Percent Recalled")+
  theme_classic()+
  geom_errorbar(width=.1, position=position_dodge(.9), aes(ymin=prop_cond-ci, ymax=prop_cond+ci))+
  scale_y_continuous(labels = scales::percent, expand = c(0,0))+
  scale_x_discrete(labels=c("control" = "Control","mid"= "Low Switch", "high" = "High Switch"))+
    scale_fill_manual(values = c("grey60", "darkorchid4", "darkgreen"))
```

```{r}
between_condition_bind_fin_v2 <- rbind(condition_same_fin2, condition_novel_fin2)

between_condition_bind_fin_v2 <- between_condition_bind_fin_v2 %>% 
  mutate(between_condition = case_when(N == 83 ~"same",
                                       N == 84 ~ "novel"))


v2_final_11 <- between_condition_bind_fin_v2 %>% 
  ggplot(aes(x = condition, fill = interaction(between_condition,condition), y = prop_cond)) +
  geom_bar(position="dodge", stat="identity", color = "black", size = .3, alpha = .8) +
  labs(title    = "Percentage of Recalls by Condition and Task",
         x        = "Condition",
         y        = "Percent Recalled")+
  theme_classic()+
  geom_errorbar(width=.1, position=position_dodge(.9), aes(ymin=prop_cond-se, ymax=prop_cond+se))+
  scale_y_continuous(labels = scales::percent_format(accuracy = 1L), expand = c(0,0))+
  scale_x_discrete(labels=c("control" = "Control","mid"= "Low Switch", "high" = "High Switch"))+
  scale_fill_manual(name = "Condition", values=c("grey60", "grey20", "darkseagreen2", "darkgreen", "lavender", "darkorchid4")) +
  facet_wrap(~between_condition)


ggsave(plot=v2_final_11, width = 8, height = 5, filename="~/v2_final_11_se_newcoding.pdf")

```

```{r}
#models


#same 
model_condition_same_11_v2_fin <- glmer(recalls_final~condition +list_half+blocknum_contin + (1|subject)+ (1|word_enc), family = binomial, data = sf11_total_same_fin_v2)
summary(model_condition_same_11_v2_fin)

plot_model(model_condition_same_11_v2_fin, type = "pred")

#novel 

sf11_total_novel_fin_v2<- sf11_total_novel_fin_v2 %>% 
  mutate(condition = fct_relevel(condition, "high", "control", "mid"))

model_condition_novel_11_v2_fin <- glmer(recalls_final~condition +list_half+blocknum_contin + (1|subject)+ (1|word_enc), family = binomial, data = sf11_total_novel_fin_v2)
summary(model_condition_novel_11_v2_fin)

plot_model(model_condition_novel_11_v2_fin, type = "pred")


#all

sf11_total_final_v2 <- rbind (sf11_total_novel_fin_v2, sf11_total_same_fin_v2)


model_condition_total_11_v2_fin <- glmer(recalls_final~condition*between_condition +list_half+blocknum_contin + (1|subject)+ (1|word_enc), family = binomial, data = sf11_total_final_v2)
summary(model_condition_total_11_v2_fin)


sf11_total_final_v2_high <- sf11_total_final_v2 %>% 
  filter(condition == "high"| condition == "control")


model_condition_total_11_v2_fin_high <- glmer(recalls_final~condition*between_condition +list_half+blocknum_contin + (1|subject)+ (1|word_enc), family = binomial, data = sf11_total_final_v2_high)
summary(model_condition_total_11_v2_fin_high)

```




```{r}
#spc final mid 
detach(package:Rmisc)
detach(package:plyr)

spc_mid_v2_11_tally <- sf11_total_final_v2_mid_spc2 %>% 
  group_by(subject, trialnum_new) %>% 
  tally() 
spc_mid_v2_11_tally


spc_mid_v2_11 <- sf11_total_final_v2_mid_spc2 %>% 
  dplyr:: select(subject, trialnum_new, between_condition, recalls_final) %>% 
  group_by(subject, trialnum_new, between_condition) %>% 
  mutate(sum_recall2 = sum(recalls_final)) %>% 
  summarise(mean_rec_cond = mean(sum_recall2)) 


merged_spc <- merge(spc_mid_v2_11,spc_mid_v2_11_tally)


merged_spc <- merged_spc %>% 
  mutate(prop_cond = mean_rec_cond/n)


library(Rmisc)

spc_mid_11_v2 <- summarySEwithin(merged_spc, measurevar="prop_cond", withinvars = c("trialnum_new", "between_condition"),idvar = "subject", na.rm=FALSE, conf.interval=.95)

spc_mid_11_v2<- spc_mid_11_v2 %>% 
  mutate(trialnum_new = fct_relevel(trialnum_new, "switch", "repeat1", "repeat2", "repeat3"))


v2_mid_spc_11 <- spc_mid_11_v2 %>% 
  ggplot(aes(x = trialnum_new, fill = interaction(between_condition,trialnum_new), y = prop_cond)) +
  geom_bar(position="dodge", stat="identity", color = "black", size = .3, alpha = .8) +
  labs(title    = "Percentage of Recalls by Condition and Task",
         x        = "Transition Type",
         y        = "Percent Recalled")+
  theme_classic()+
  geom_errorbar(width=.1, position=position_dodge(.9), aes(ymin=prop_cond-ci, ymax=prop_cond+ci))+
  scale_y_continuous(labels = scales::percent, expand = c(0,0))+
  scale_fill_manual(name = "Transition Type", values=c("grey60", "grey20", "darkseagreen2", "darkgreen", "grey60", "grey20","lavender", "darkorchid4")) +
  facet_wrap(.~between_condition)



v2_mid_spc_11_lines <- spc_mid_11_v2 %>% 
  ggplot(aes(x = trialnum_new, y = prop_cond)) +
  geom_line(aes(group = between_condition, color = between_condition), position=position_dodge(.3))+
  labs(title    = "Percentage of Recalls by Condition and Task",
         x        = "item in event",
         y        = "Percent Recalled")+
  theme_classic()+
    geom_errorbar(width=.1, position=position_dodge(.3), aes(group = between_condition, color = between_condition, ymin=prop_cond-ci, ymax=prop_cond+ci))+
    geom_point(aes( group = between_condition, color = between_condition), position=position_dodge(.3))+
  scale_y_continuous(labels = scales::percent_format(accuracy = 1L), expand = c(0,0), limits = c(.15,.4))+
  scale_color_manual(name = "group", values=c("grey60", "grey20")) 


ggsave(plot=v2_mid_spc_11_lines, width = 6, height = 5, filename="~/v2_mid_spc_11_lines.pdf")

```


```{r}
sf11_total_v2_mid_spc_model_total_fin<- aov(recalls_final~trialnum_new*between_condition + (1|subject), data = sf11_total_final_v2_mid_spc2)

summary(sf11_total_v2_mid_spc_model_total_fin)


```



```{r}
#boundary vs preboundary 

detach(package:Rmisc)
detach(package:plyr)


sf11_total_v2_mid_spc_final_3<- sf11_total_final_v2 %>% 
  filter(condition == "mid") %>% 
  filter(trialnum == "5" | trialnum == "6" |trialnum == "8" |trialnum == "9" |trialnum == "10" |trialnum == "12") %>%
  mutate(trialnum_new = case_when(trialnum == "5" ~ "boundary",
                                  trialnum == "6" ~ "postboundary",
                               trialnum == "8" ~ "preboundary",
                               trialnum == "9" ~ "boundary",
                               trialnum == "10" ~ "postboundary",
                               trialnum == "12" ~ "preboundary")) 



spc_mid_v2_11_tally_final2 <- sf11_total_v2_mid_spc_final_3 %>% 
  group_by(subject, trialnum_new) %>% 
  tally() 
spc_mid_v2_11_tally_final2


spc_mid_v2_11_final2 <- sf11_total_v2_mid_spc_final_3 %>% 
  dplyr:: select(subject, trialnum_new, between_condition, recalls_final) %>% 
  group_by(subject, trialnum_new, between_condition) %>% 
  mutate(sum_recall2 = sum(recalls_final)) %>% 
  summarise(mean_rec_cond = mean(sum_recall2)) 


merged_spc_final2 <- merge(spc_mid_v2_11_final2,spc_mid_v2_11_tally_final2)


merged_spc_final2 <- merged_spc_final2 %>% 
  mutate(prop_cond = mean_rec_cond/n)


merged_spc_final2<- merged_spc_final2 %>% 
  mutate(trialnum_new = fct_relevel(trialnum_new, "preboundary", "boundary", "postboundary"))


library(Rmisc)

spc_mid_11_v2_final2 <- summarySEwithin(merged_spc_final2, measurevar="prop_cond", withinvars = c("trialnum_new", "between_condition"),idvar = "subject", na.rm=FALSE, conf.interval=.95)


v2_spc_sf11_bound_final <- spc_mid_11_v2_final2 %>% 
  ggplot(aes(x = trialnum_new, fill = interaction(between_condition,trialnum_new), y = prop_cond)) +
  geom_bar(position="dodge", stat="identity", color = "black", size = .3, alpha = .8) +
  labs(title    = "Percentage of Recalls by Condition and Task",
         x        = "Transition Type",
         y        = "Percent Recalled")+
  theme_classic()+
  geom_errorbar(width=.1, position=position_dodge(.9), aes(ymin=prop_cond-se, ymax=prop_cond+se))+
  scale_y_continuous(labels = scales::percent_format(accuracy = 1L), expand = c(0,0))+
  scale_fill_manual(name = "Transition Type", values=c("grey60", "grey20", "darkseagreen2", "darkgreen", "grey60", "grey20","lavender", "darkorchid4")) +
  facet_wrap(.~between_condition)

ggsave(plot=v2_spc_sf11_bound_final, width = 8, height = 5, filename="~/v2_spc_sf11_bound_final_se.pdf")
```



```{r}
sf11_total_v2_mid_spc_final_3_cond <- sf11_total_v2_mid_spc_final_3 %>% 
  filter(between_condition == "novel")

model_spc_mid_3_final<- glmer(recalls_final~trialnum_new+ blocknum_contin + (1|subject)+ (1|word_enc) + (1|latency), family = binomial, data = sf11_total_v2_mid_spc_final_3_cond)
summary(model_spc_mid_3_final)

plot_model(model_spc_mid_3_final, type = "int")
```

